### ISSUE TITLE
10bit AVC encoding?

### ISSUE THREAD

**Issue by Selur** [rigaya/QSVEnc#1]
since 'check-features'  shows:

>Codec: H.264/AVC
             CBR   VBR   AVBR  QVBR  CQP   VQP   LA    LAHRD ICQ   LAICQ VCM
10bit depth   x     x     x     x     x     x     x     x     x     x     x

and profile only shows:
- H.264: auto(default), Baseline, Main, High
- HEVC:  auto(default), main, main10

I was wondering:
How to enable 10bit AVC encoding on Kaby Lake CPUs?
(for HEVC one can select main10, but there is no High10 listed)

Or doesn't QSV support 10bit AVC encoding?

**Comment by rigaya** [comment]
Unfortunately, 10bit QSV encode is only for HEVC, and not for AVC on Kabylake, so High10 for AVC is not listed.

**Comment by Selur** [comment]
Thanks for clearing that up. :)
