### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by hmartin417** [rigaya/QSVEnc#101]
With QSV supporting Deep Link and reading some threads about an API that would support using 2 GPUs simultaneously with Blender, could you add/create an API for this feature as well to QSVEncC? I have A750.

**Comment by rigaya** [comment]
I'm not sure what you exactly mean by the "Blender" thing, but we already have [--hyper-mode](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--hyper-mode-string) to use dGPU and iGPU simultaneously.

Please note that it seem to require Intel Arc GPU to be primary GPU.

**Comment by hmartin417** [comment]
Blender is a graphic program. It can utilize 2 A750 GPU cards at the same time to increase encoding speed.

**Comment by rigaya** [comment]
There are no plans for supporting multi dGPUs.

I think it's difficult for a system expecting multi Arc GPUs.
