### ISSUE TITLE
Commands being ignored A750

### ISSUE THREAD

**Issue by hmartin417** [rigaya/QSVEnc#102]
During the encoding process, there are many commands that are ignored. The biggest that i have found is the ignoring of what audio streams to copy. Trellis seems to be ignored as well along with async-depth. I also had to remove setting of the tier. it would fail when i had it set to high. It still just copies them all. I have added the syntax below along with a screenshot.
syntax:
%QSVenc% -i "%%a" --avhw --hyper-mode on --device 1 --format matroska --input-analyze 90 --codec hevc --qvbr-quality 29 --profile main10 --ref 5 --bframes 7 --b-pyramid --adapt-ltr --strict-gop --gop-ref-dist 8 --avsync forcecfr --async-depth 0 --output-buf 128 --fallback-rc --no-repeat-pps --no-tskip --sao none --fixed-func --max-bitrate 8000 --trellis off --output-depth 10 --video-metadata clear --audio-metadata clear --metadata clear --chapter-copy --colormatrix auto --transfer auto --colorprim auto --master-display copy --max-cll copy --chromaloc auto --colorrange auto --audio-copy 1,2 --sub-copy eng --chapter-copy --metadata title="%%~na" --video-metadata title="%%~na" --video-metadata language=English --log "E:\Logs\%%~na.txt" -i "%%a" -o "%cd%\MUXED\%%~na.video" & goto:end

![Capture](https://user-images.githubusercontent.com/53615777/205291840-da694e81-5977-402d-9def-3137437a735d.JPG)

**Comment by hmartin417** [comment]
Ignoring audio:
I want to only mux track 1 and 2 to my output file. the audio-meta clear will clear all tracks meta which i want. i dont want all of the audio tracks though. SO it is not recognizing that i only want audio tracks 1 and 2 and instead defaulting to adding them all.

Trellis:
Yes, it does show in the top that it is disabled/not supported at the top. In my syntax, i already have it turned off  so it shouldnt even be trying to use it. The clip also still shows trellis as auto.

I will remove the gop-ref-dist then.

this entire script i use has been working for years on a RTX card with no issues. I have had to change a few commands as they are not in quicksync, but most of it is still there.

**Comment by rigaya** [comment]
>  it is not recognizing that i only want audio tracks 1 and 2 and instead defaulting to adding them all.

This is because you are using ```--audio-metadata clear```. This should be replaced to ```--audio-metadata 1?clear --audio-metadata 2?clear```.

> trellis as auto

It means off for HEVC, actually available only for H.264 now. Therefore you can just remove the options or simply ignore it.

**Comment by hmartin417** [comment]
Thank you for clarifying that it needs to be that way. Apparently Quicksync handles them differently than NVidia. How do i get lookahead??

How would you set the below in QSV?
-c hevc --vbrhq 0 --vbr-quality 28 --qp-init 20:22:25

**Comment by rigaya** [comment]
Please not that QSV is **not** NVENC, it is a **different** encoder, thus it **does not have the same/equivalent options or behavior**.

NVEnc ```--lookahead``` is separate rate control mode [--la](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--la-int---la-lookahead-mode) in QSVEnc, however, only supported in H.264. Therefore cannot be used with HEVC encoding.

You might want to try [--icq](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--icq-int-icq-intelligent-const-quality-mode-default-23) instead of NVEnc ```--vbrhq 0 --vbr-quality 28```. There are no equivalent option in QSVEnc to ```--qp-init```.

**Comment by hmartin417** [comment]
Ok. Thanks for all the help and details!

**Comment by hmartin417** [comment]
Could you provide any detail on how to load DV back into the encode?

**Comment by rigaya** [comment]
Setting dolby visio nprofile can be done by [--dolby-vision-profile](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--dolby-vision-profile-float), and rpu data can be imported by [--dolby-vision-rpu](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--dolby-vision-rpu-string).

Rpu data can be extracted using [dovi_tools](https://github.com/quietvoid/dovi_tool) from input file.

Please note that not all dolby vision data is supported, only single-layer profiles are supported. Also please refer to notes in [--dolby-vision-rpu](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--dolby-vision-rpu-string).

**Comment by hmartin417** [comment]
Any chance you can make a copy function like with hdr?

**Comment by rigaya** [comment]
I'll close this issue, as there is no plan for copy function of dolby vision, as I don't have enough knowledge for that.
