### ISSUE TITLE
--sub-source results in Error: Failed to write subtitle stream # frame: Invalid argument.

### ISSUE THREAD

**Issue by bavdevc** [rigaya/QSVEnc#109]
Hello @rigaya 

I tried adding an external PGS subtitle to the encoding process using the --sub-source option but it will always result to the following error message and the qsvenc aborts:

> [matroska @ 00000182603214c0] Application provided invalid, non monotonically increasing dts to muxer in stream 3: 119800 >= 119797
avout: Error: Failed to write subtitle stream 3 frame: Invalid argument.

**workaround:** remux the input mkv file and the subtitle with MKVToolNix/mkvmerge into a new mkv file, then qsvenc runs without any error and the resulting file is correct incl. the subtitle and all the other specified options for that subtitle stream

**Comment by bavdevc** [comment]
no problem, workaround is fine for me - take all the time you need and tell me if you need help with testing something - atm. I'm creating a lot of CI/CD test cases for Intel GPU driver / ffmpeg / qsvenc and some automation scripts

**Comment by rigaya** [comment]
Thanks. The fix for this issue is now in the code but currently disabled, I'll update ffmpeg dlls once I've gone through tests to make sure the app works fine with the new dlls.

**Comment by rigaya** [comment]
[QSVEnc 7.30](https://github.com/rigaya/QSVEnc/releases/tag/7.30) updates ffmpeg libs and now PGS subtitles file can be muxed in with [--sub-source](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--sub-source-stringintparam1value1).

Thanks again for reporting this issue.

**Comment by bavdevc** [comment]
Hello rigaya,

I have good news and bad news after testing the 7.30 release.

good news:
--sub-source now works without any error that breaks qsvenc

bad news:
all subtitles, using --sub-copy or --sub-source turn out empty / 0 bytes in the resulting file when using 7.30 - working fine in 7.29

btw. there is a little typo in the https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md for --sub-source:

Example2: --sub-source "<sub_file>":disposition=default;metadata=language=jpn
should be
Example2: --sub-source "<sub_file>:disposition=default;metadata=language=jpn"

otherwise you get a command line error

**Comment by rigaya** [comment]
Thank you, I made another fix with [QSVEnc 3.33](https://github.com/rigaya/QSVEnc/releases/tag/7.33) fixing this problem.

**Comment by bavdevc** [comment]
re-test with 7.33 successful --sub-source now works without any error and the output is correct

fabulous work!!! Thank you very much
