### ISSUE TITLE
Media SDK 2018 R2

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#11]
Intel did release a new Media SDK recently: https://software.intel.com/en-us/blogs/2018/08/01/whats-new-in-intel-media-sdk-for-windows-2018-r2

Anything new?

**Comment by rigaya** [comment]
New VPP Motion Compensate Temporal Filter (MCTF) has been added, I've added option for it ([--vpp-mctf](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-mctf-auto-or-int)) in QSVEnc 3.10.

**Comment by rigaya** [comment]
I'll close this issue, as I think the topic has been answered.
