### ISSUE TITLE
sound encoding with AAC-HE seems to be broken

### ISSUE THREAD

**Issue by FlorianGamper** [rigaya/QSVEnc#111]
Version 7.29 : Windows

When Trying to encode sound as AAC-HE,
I end up with a corrupted file that is not playable, and MKVToonix says, the "Malformed AAC codec initalization data found"

parameters are "--audio-codec aac --audio-bitrate 64 --audio-profile HE-AACv2 
when using HE-AAC the same happens

this is what mediainfo says about the sound

```
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Codec ID                                 : A_AAC-29
Duration                                 : 1 min 22 s
Bit rate                                 : 2 211 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 96.0 kHz
Frame rate                               : 1 199.684 FPS (960 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -21 ms
Stream size                              : 21.7 MiB (89%)
Title                                    : Stereo
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray
```

**Comment by FlorianGamper** [comment]
Original sound is a 48Khz Ac3 2.0

**Comment by rigaya** [comment]
The default aac encoder supports AA-LC only, unfortunately it is not possible to encode to HE-AAC or HE-AACv2.

--audio-profile options is for other encoders such as libfdk_aac which can actually use HE-AAC or HE-AACv2. However, it is not included in my build, as it is not allowed to distribute in binary due to it's license conflict with (L)GPL.

**Comment by FlorianGamper** [comment]
@rigaya : 
Is there a tutorial how to build it with libfdk_aac ? 
I can only find the standard description

**Comment by FlorianGamper** [comment]
@forart : exhale is nice, but my appletv can't play it directly

**Comment by forart** [comment]
> Is there a tutorial how to build it with libfdk_aac ? I can only find the standard description

RareWares is your friend: https://www.rarewares.org/aac-encoders.php

**Comment by rigaya** [comment]
> Is there a tutorial how to build it with libfdk_aac ?

No tutorial will be provided for a custom build.
