### ISSUE TITLE
XeSS possible?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#112]
Hello,

I've seen that for NVEnc it is now possible with rtx cards to use AI  superresolution.

Would similar be possible for QSVEnc with the XeSS SDK?

`https://github.com/intel/xess`

**Comment by rigaya** [comment]
I looked through the XeSS SDK, the interface of XeSS is DirectX12(DX12), which requires knowledge of 3D graphics (which I'm not bright in).

Therefore, I think this is difficult to be implemented.

NVEnc (nvvfx) was much easier for me, as it's interface was CUDA.

**Comment by quamt** [comment]
Ok. Thank you for looking into it.
I'll close this in that case.
