### ISSUE TITLE
Usage of hypermode and h.265 results in error

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#113]
When I try to encode a file with the A770 and Intel 12Gen CPU I get an error message when the usage of hyper mode with HEVC

Is it possible to see what exactly causes the error message.

the line below works with no problems.
`"QSVEncC64.exe" -i "input.mp4" --audio-copy --hyper-mode adaptive -o "output.mkv"`

The one below creates an error
`"QSVEncC64.exe" -i "input.mp4" -c hevc --audio-copy --hyper-mode adaptive -o "output.mkv"`

Error message is:
```
Failed to initialize encoder. : invalid video parameters.
avout: failed to write header for output file: Invalid data found when processing input
QSVEncC.exe finished with error!
```
Is the hyper mode limited to H.264?

More info:

```
QSVEncC (x64) 7.34 (r2999) by rigaya, Feb 13 2023 12:32:42 (VC 1934/Win)
OS             Windows 11 x64 (22621) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [5.00GHz] (8P+8E,16C/24T) <DG2>
GPU Info       Intel Arc A770 Graphics (512EU) 300-2400MHz (31.0.101.4091)
Media SDK      QuickSyncVideo (hardware encoder) FF, 2nd GPU, API v2.08
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 23 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 24000/1001 fps
AVSync         cfr
```

**Comment by rigaya** [comment]
Hyper mode should also work with HEVC.

![image](https://user-images.githubusercontent.com/815947/218746953-054787c5-7d80-4267-a652-2770be0972d5.png)

---
From your log, it looks like A770 is the 2nd GPU.
```
 Media SDK      QuickSyncVideo (hardware encoder) FF, 2nd GPU, API v2.08
```
Arc GPU is better to be seen as 1st GPU when using hyper encode.

I'm actually not sure, but this might be changed by Windows settings. (I'm sorry my capture is in Japanese.)

In the Windows settings, [System] > [Display] > [Graphics], add QSVEncC64.exe as application.

![image](https://user-images.githubusercontent.com/815947/218747553-d66c5646-f710-40c7-ad7b-609c216cbcf6.png)

And from the options, select Arc GPU to be used for QSVEncC and save.

![image](https://user-images.githubusercontent.com/815947/218747937-50bea0c6-8861-44df-8988-3cb4e8a3a700.png)

This might change the behavior.

**Comment by quamt** [comment]
Thank you @rigaya.
It works now.

```
QSVEncC (x64) 7.34 (r2999) by rigaya, Feb 13 2023 12:32:42 (VC 1934/Win)
OS             Windows 11 x64 (22621) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [5.12GHz] (8P+8E,16C/24T) <DG2>
GPU Info       Intel Arc A770 Graphics (512EU) 300-2400MHz (31.0.101.4091)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU, API v2.08
Async Depth    8 frames
Hyper Mode     on
Buffer Memory  d3d11, 169 work buffer
```
