### ISSUE TITLE
Adding/Embedding fonts in MKV

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#116]
Hello @rigaya 

I want to check if it is possible to add fonts to mkv files, same as mkvtoolnix does when encoding the files?
This would be especially helpful for subtitles in `ASS `format.

I saw this option ` --attachment-source` but not sure if this can be used for fonts and if yes, what the mimetype would be.

Thank you

**Comment by quamt** [comment]
I did try `--attachment-source "arial.ttf":metadata=mimetype=font/ttf`
But this errors out with:

```
Error: Unknown option: font/ttf

Did you mean option(s) below?
  --output
QSVEncC.exe finished with error!
```

**Comment by rigaya** [comment]
I have added example of using --attachment-source with fonts on the [documents](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--attachment-source-stringintparam1value1).

**Comment by quamt** [comment]
Thank you @rigaya 
Will report back.

**Comment by quamt** [comment]
@rigaya 

Thank you.
Works:
Attachments                              : ARIAL.TTF / TREBUC.TTF / VERDANA.TTF
