### ISSUE TITLE
AVBR HEVC

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#12]
Can we get AVBR for HEVC? According to latest release notes it is supported. 

HEVC encode limitations:

Supports only CQP, CBR, VBR, ICQ and **AVBR** rate control methods, as well as MFX_RATECONTROL_LA_EXT with lookahead plugin.

**Comment by rigaya** [comment]
Whenever I set AVBR mode for HEVC, the driver returns incompatible parameter and changes mode to VBR (on Core i7 7700K).

Maybe supported on more new CPUs?

**Comment by mikk9** [comment]
I don't know, did you try the latest driver? Maybe it wasn't supported in earlier drivers.

**Comment by mikk9** [comment]
It says not supported. This is odd when Intel says it is supported, I may ask them.
