### ISSUE TITLE
Multi-Format Codec Engines

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#120]
Hello @rigaya ,

I want to check.

On the intel webpage for the A770 
`https://www.intel.sg/content/www/xa/en/products/sku/229151/intel-arc-a770-graphics-16gb/specifications.html`
 it says Multi-Format Codec Engines 2
```
Multi-Format Codec Engines
Multi-Format Codec Engines provide hardware encoding and decoding for amazing video playback, content creation, and streaming usages.
```

Does that mean it can run two encodes at the same time without affecting the other engine?
I didn't see the 2 engines in the features check. 
Or did I misunderstand?

**Comment by rigaya** [comment]
> I didn't see the 2 engines in the features check.

Feature check is checking per device (GPU), and not per engine.

With Arc A380 which also shown to have 2 engines, I can get half the throughput per process when running 2 process at the same time.(total throughput is the same.)

It might be that oneVPL API automatically use 2 engines, but not sure about that, there is no way to check.

**Comment by quamt** [comment]
Ok. Thank you.
