### ISSUE TITLE
issue with y4m file

### ISSUE THREAD

**Issue by Joet73** [rigaya/QSVEnc#121]
Hi,

There is a chroma shifting issue when using y4m input file using the below command line
`QSVEncC64--y4m -i input.y4m --icq 18 -c hevc -u best -o output.mp4`
Switching to this ffmpeg piping command line no chroma shift
`ffmpegg -y -i input.y4m -an -f yuv4mpegpipe - | QSVEncC64 --y4m -i - --icq 18 -c hevc -u best -o output.mp4`

Tested on Windows 11, latest Qsvenc 7.35.
 Source file used can be downloaded [here](https://media.xiph.org/video/derf/y4m/park_joy_2160p50.y4m) 

BTW, exact same issue with the nvenc 7.20

**Comment by rigaya** [comment]
I've checked the file, but seems to lack colorspace parameter ('C420') in the header, causing error in chroma pixel handling.
