### ISSUE TITLE
qsvenc --trim --audio-codec

### ISSUE THREAD

**Issue by sir0drake** [rigaya/QSVEnc#125]
hello rigaya,

i am missing an option for people like me not very interisted to change the audio-format within a video-file.

i use --trim  and missing an option, to trim also "all" Audio-files inside without encode again
or to encode into the same format.

--audio-copy  do not fit this requirement (  only video-track will be trim, audio not. stay in full length ) 
and once i started use --audio-codec without details 
mostly aac-lc will be used for the most of my audio formats.
mp2->aac lc
mp3->aac lc
ac3 -> aac lc
ect...

is there a chance to enhance the logic to come into this direction i need  ? 

best regards and thanks also for your good job you are doing here 

ps. same is also needed in VCEEncC.exe   no need to open a seperate issue

**Comment by rigaya** [comment]
I think that --trim and --audio-copy should be able to work together fine as far as I have tested.

**Comment by rigaya** [comment]
I'll close this issue as the topic was answered.
