### ISSUE TITLE
Add Logo or Watermark

### ISSUE THREAD

**Issue by wwaag76** [rigaya/QSVEnc#128]
Is there currently an option to add a logo or watermark similar to ffmpeg's overlay?  I looked at the help file but could not find it.  If not, could it be added?

**Comment by rigaya** [comment]
You might want to try a filter [—vpp-overlay](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-overlay-param1value1param2value2) which is close to ffmpeg overlay filter. Please note that it has limited features compared to the one in ffmpeg.

**Comment by wwaag76** [comment]
Works great.  I was looking at a help file from a previous build.
