### ISSUE TITLE
Linux: Dolby Vision options not enabled

### ISSUE THREAD

**Issue by bavdevc** [rigaya/QSVEnc#129]
Hello @rigaya 

atm. I'm testing the Linux build with the latest 6.2.6 kernel and the 2023.1.1 libvpl - some more features in libvpl / media-driver are working now compared to my last test in 2022. Intel is still working on fixing bugs and making it more feature complete compared to the windows version.

one thing I noticed:
_Error: Unknown option: --dolby-vision-profile
Error: Unknown option: --dolby-vision-rpu_

those options are disabled in the linux build because of **#define ENABLE_DOVI_METADATA_OPTIONS** is only set for windows within **rgy_version.h**

solution:
I just added the **#define ENABLE_DOVI_METADATA_OPTIONS 1**
in the else/linux section, re-compiled qsvenc
and it's working fine. Tested with QVBR encode because of:
**Please use Bitrate Mode - CBR/Bitrate Mode - VBR/Bitrate Mode - AVBR/VCM (Video Conference Mode)/Quality VBR bitrate mode for dolby vision output.**
--> resulting file contains the RPU data and can be extracted again with dovi_tool

kind regards

**Comment by rigaya** [comment]
Thank you for letting me know the issue.

I've already committed and pushed the fix, and will be there in the next release.

**Comment by bavdevc** [comment]
ok, I'm closing this one as the commit it already done for the next version

kind regards
