### ISSUE TITLE
How to use --tune?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#132]
Hello @rigaya,

How should the new option `--tune` be used?
There is no difference when setting it in the result.
Is there any specific setting that needs to be set for it to be triggered?

**Comment by rigaya** [comment]
--tune option requires API 2.9 support, but the latest 4255 Win driver is still at API 2.8, so we’ll need to wait for driver update.

**Comment by quamt** [comment]
Ok. Thank you :-)
