### ISSUE TITLE
hdr2sdr colorprim ignored

### ISSUE THREAD

**Issue by holmy88** [rigaya/QSVEnc#134]
colorprim setting is being ignored when using hdr2sdr and is always doing bt2020:bt709 when I'm trying to use st432-1:bt709. This was fixed up in nvencc last year if that solution can be duplicated.

**Comment by rigaya** [comment]
Thank you for letting me know the issue, [QSVEnc 7.39](https://github.com/rigaya/QSVEnc/releases/tag/7.39) has ported fix from NVEncC.

**Comment by holmy88** [comment]
Just tried it, colorprim setting still being ignored and doing bt2020:bt709 instead. My full command below

"C:\Temp\bin\encc\qsvencc64.exe" --avhw -i "C:\Temp\Thread1\video_in.mkv" --avsync forcecfr --crop 0,276,0,276 --codec hevc --output-depth 10 --quality 1 --qvbr 17800k --qvbr-quality 20 --fallback-rc --max-bitrate 19580k --vbv-bufsize 17800k --la-depth 100 --gop-len 50 --hyper-mode adaptive --i-adapt --b-adapt --adapt-ref --adapt-ltr --b-pyramid  --tskip --sao none --vpp-colorspace hdr2sdr=reinhard,source_peak=10000,peak=4000,desat_strength=1,colorprim=st432-1:bt709,matrix=bt2020nc:bt709,transfer=smpte2084:bt709 --colormatrix bt709 --colorprim bt709 --transfer bt709 --colorrange limited -o "C:\Temp\Thread1\video_out.mkv" 

![image](https://github.com/rigaya/QSVEnc/assets/110201985/82ac1db5-025c-4a58-a5e7-7d53dae8a037)

**Comment by rigaya** [comment]
The problem was the handling of colorprim when using hdr2sdr. [QSVEnc 7.40](https://github.com/rigaya/QSVEnc/releases/tag/7.40) should have fixed this issue.

**Comment by holmy88** [comment]
Just tested with my script, I can confirm it is now working. Thank you.

**Comment by rigaya** [comment]
I'll close this issue, as the problem should have been fixed.
