### ISSUE TITLE
Encode engine crash and hang

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#135]
Hello @rigaya,

When using 
```
--async-depth 1024
--input-buf 10240
--output-buf 128
```

Everything works fine 
as `--async-depth 1024` is max for that setting and `--output-buf 128` is the max for this setting.
However, when I increase `--input-buf 10240` it crashes the encoding engine.

What I mean by crash is that at a certain setting it shows that the device cannot be loaded.
It will fallback to the iGPU (Intel CPU). I was not able to figure out as why that happens and what exactly triggers it. 

However, when it happens I need to restart the PC as it will no longer allow me to encode with the relevant engine.
Example: It crash with HEVC, I can still use the AV1 encoder with no issue.
Usage of "Win + Ctrl + Shift + B" doesn't help.

I couldn't find if there is a limit to the `--input-buf ` as I do not get any message like you would get when you set the Async Depth more as 1024, for example.

**Comment by rigaya** [comment]
Those settings are simply using to much memory at that values, no wonder it crushes or hangs!

It is not expected to be used in such a large value, I don’t think raising to that much values are useful in any way.

It is not recommended to use such large values, reduce the parameters to near default values or just leave it default and you’ll be fine.
