### ISSUE TITLE
Unable to detect my A770 16GB

### ISSUE THREAD

**Issue by BuyMyMojo** [rigaya/QSVEnc#137]
I was trying to run an AV1 encode and got this error:
```
d3d11: D3D11Device: D3D11CreateDevice: -2147024882
Failed to get HW device handle. : undeveloped feature.
QSVDevice::init: failed to create allocator: undeveloped feature..
```

so I tried again with `--disable-d3d` which gave me this error: `AV1 encoding is not supported on current platform.`

So finally I ran `QSVEncC64 --check-environment` and it says I have no GPU installed and that D3D11CreateDevice fails

```
QSVEncC (x64) 7.38 (r3072) by rigaya, May  2 2023 07:45:16 (VC 1934/Win)
 Intel Media SDK API v2.09
 reader: raw, avi, avs, vpy, avsw, avhw
D3D11CreateDevice failed
Environment Info
OS : Windows 11 x64 (22621) [UTF-8]
CPU: AMD Ryzen 5 5600X 6-Core Processor [4.85GHz] (6C/12T)
RAM: Used 16733 MB, Total 32691 MB
GPU: 
```

The GPU section is just blank.

CPU: 5600x
GPU: Arc A770 16GB
Driver: 31.0.101.4335
OS: Windows 11 22H2 v22621.1555

**Comment by quamt** [comment]
Did you check if all the drivers are up to date? AMD chipset, Intel driver etc.

The GPU is visible in the device manager?

AMD Smart Access Memory is enabled? (Resizable BAR)
`https://www.techarp.com/computer/guide-smart-access-memory/`

Which mainboard are you using is the Smart Access Memory in BIOS available? 
You can use CPU-Z to check the BIOS version and mainboard manufacturer.

**Comment by BuyMyMojo** [comment]
I found the issue, with the latest GPU drivers something can cause the GPU's encoder to just be inaccessible until a reboot which was the case.

I don't entirely know what causes this issue on the A770 yet but hopefully it will be fixed in a future driver update
