### ISSUE TITLE
Concat option for multiple files?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#141]
Hello @rigaya,

Is it possible, like in FFmpeg, to do a concat of files? 
I didn't see an option for that.

In FFmpeg, at least Windows you create a txt file with the files that need to be concat
Example:
```
file 'video1.mp4'

file 'video2.mp4'
```

Next run command:
`ffmpeg -f concat -i filelist.txt -c copy output.mp4`

Which will output one file out of the files in the list.
I am currently using the option, but since all files are the same codec, same resolution etc. 
Is it possible to implement as that would remove one step of merging the files before encoding them.

**Comment by rigaya** [comment]
As QSVEncC supports most format and protocols of libavformat, you can try the following options.
```
QSVEncC64.exe --input-format concat -i filelist.txt -o output
```
Please note that the progress percentage will not be shown in this mode.

**Comment by quamt** [comment]
Ok. I will test that.

**Comment by quamt** [comment]
Thank you.
Btw it should be all that is mentioned here `https://ffmpeg.org/libavformat.html` 
`https://ffmpeg.org/doxygen/4.0/group__libavf.html` ?
