### ISSUE TITLE
Using Luma in unsharp

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#142]
Hello @rigaya,

I want to check for the `--vpp-unsharp` option. I see the following option in the options list.

```
--vpp-unsharp [<param1>=<value1>[,<param2>=<value2>]...]
unsharp filter, for edge and detail enhancement.

Parameters

radius=<int> (default=3, 1-9)
radius of edge / detail detection.

weight=<float> (default=0.5, 0-10)
Strength of edge and detail emphasis. Larger value will result stronger effect.

threshold=<float> (default=10.0, 0-255)
Threshold for edge and detail detection.

```

Is it possible to implement Luma for unsharp, or is it there, and I do not see it?

**Comment by rigaya** [comment]
There is no ```luma``` option supported in QSVEnc.

Please let me know the details of the algorithms and the usefullness of luma option discussed here, so I can figure out if it could be implemented or not.

**Comment by quamt** [comment]
The luma values in FFmpeg's unsharp filter specifically target the brightness information in the video. When it comes to parameters, the unsharp filter in FFmpeg accepts two sets of parameters: one for the luma (Y) and one for chroma (C).

As far as I recall the format is unsharp=lXxY:MXxMY where:

lXxY: Sets the luma matrix size. X and Y specify the width and height of the matrix.
MXxMY: Sets the luma effect amount. MX and MY specify the amount for the width and height.
For example, unsharp=7x7:1.5 sets a luma matrix of 7x7 and an effective amount of 1.5. A positive effect amount results in a sharper image, and a negative effect amount results in a blurrier image.

It should have a lesser impact on producing artefacts compared to chroma usage in unsharp.

**Comment by rigaya** [comment]
Although the filter name is the same, implementation in ffmpeg is different compared to the one in qsvencc, for example qsvencc does not have  matrix stuff but has radius, weight and threshold. Therefore, the parameters cannot be copied in to qsvencc.

What kind of problem do you have now for the filter, and why do you need separate settings for luma and chroma?

**Comment by quamt** [comment]
Multiplying the original colour by a sharpening value will make it sharper but can cause some colour fringe artefacts.

Luma sharpening splits the brightness part (the luma) from the colour part (the chroma) and then only applies it to the Luma before recombining them again.

This gets rid of any colour artefacts. Luma mode is of higher quality.

**Comment by rigaya** [comment]
I'm sorry but I don't seem to be able to add support for this.

**Comment by quamt** [comment]
@rigaya 
What is the option here that mentions Luma Key?
`https://github.com/intel/media-driver/#video-processing-features`
