### ISSUE TITLE
[REQ] live streams (RTSP TCP/UDP) input support

### ISSUE THREAD

**Issue by forart** [rigaya/QSVEnc#144]
Hi there, as always thanks for your great work.

Recently we're dealing with (4-8) RTSP streams - coming through LAN from our PTZ cameras that we use in live performances shootings - so, since your *Encs can de/en-code much faster than realtime, we wonder if it is possible to feed them directly providing streaming links.

It would be extremely useful both for acelerated decoding (live display) and/or recording: this could push the adoption of *Encs as backend by several open NVR/NetPlayer projects.

Hope that ispires.

**Comment by Saentist** [comment]
https://github.com/rigaya/QSVEnc/issues/47

**Comment by rigaya** [comment]
QSVEncC can grab live streaming like ffmpeg, as it supports libavformat.

Simple example is shown below.
```
x64\QSVEncC64.exe -i rtsp://<ip address>:<port>/mystream -o F:\temp\test.ts --audio-codec aac
```

**Comment by forart** [comment]
> QSVEncC can grab live streaming like ffmpeg, as it supports libavformat.
>
Cool (does this means that it can be [feeded from capture card](https://github.com/cdgriffith/FastFlix/issues/418) too ?), didn't get it.

....another question: can QSVEncC be used as a "hw decoding engine" only ?

To be more clear: can it be replace ffmpeg in [this kind of script](https://github.com/apple-fritter/RTSP.downmix.4-to-1_2x2/blob/main/downmix.sh) ?

Thanks in advance !

**Comment by Saentist** [comment]
It will be interesting Zoneminder with QSVEncC

**Comment by rigaya** [comment]
I've adjusted the behavior for camera input, [QSVEnc 7.40](https://github.com/rigaya/QSVEnc/releases/tag/7.40) should be able to capture "dshow" camera input.

```
x64\QSVEncC64.exe --input-format dshow -i video="<webcam>" -o output.mp4
```

> QSVEncC be used as a "hw decoding engine" only ?

Unfortunately not, QSVEncC is designed to be used as a encoder. Also, it's design is to be able to handle single video stream. It will be difficult to re-design it to handle multiple video streams.
