### ISSUE TITLE
[Feature Requst] Add check features for multiple devices

### ISSUE THREAD

**Issue by cdgriffith** [rigaya/QSVEnc#145]
I have a user who has a an ARC GPU as well as iGPU from the CPU. It will only show the features for the device connected to a monitor. 

With hdmi connected to iGPU: https://pastebin.com/2qAypjCL
When connected to ARC: https://pastebin.com/q7tzdftK

However, the user wants to encode on the ARC while plugged into the iGPU. That works fine, however it means I don't have a way with FastFlix to know the true capabilities of the user's computer. So as is the option for AV1 wouldn't show up for that user. (Going to change for now to display all options if they have QSVEnc, so not breaking my program at all, just would be a nice feature!) 

Would be nice if it worked like NVEnc that you can provide device number https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--check-features-int

**Comment by rigaya** [comment]
We can already check different devices in current release.

My system has Arc A380 and UHD770 iGPU, I can check both GPU like below.

- Check device 1(Arc A380)
  ```
  QSVEncC64.exe --check-features --device 1
  ```

- Check device 2 (UHD770)
  ```
  QSVEncC64.exe --check-features --device 2
  ```

**Comment by cdgriffith** [comment]
Ah didn't realize you had to provide the device parameter separate from the check features one, the difference between the encoders threw me off. Thank you for the fast reply!
