### ISSUE TITLE
v7.43 bugged

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#146]
when I replaced the files in staxrip (2.19.00), I did not automatically determine that this was not a new version and continued to work.

before when I changed it, then I determined that it was new and offered to change the name

replaced NVEnc with the new files

Everything is fine

**Comment by rigaya** [comment]
> continued to work.
> Everything is fine

I'm sorry, but I don't get the point. What problem do we have here?

**Comment by Discograp** [comment]
ok

**Comment by Dendraspis** [comment]
Sorry Rigaya, nothing wrong with your release (and StaxRip), everything is fine.

I recommend to close this issue .... and forget it. 😅
