### ISSUE TITLE
<Feature Request> VPPHVS Denoiser

### ISSUE THREAD

**Issue by thx4ever** [rigaya/QSVEnc#147]
Its possible to add the filter VPPHVS denoiser to QSVEncc?
This features are avaliable on ARC Graphics currently used by intel sample_multi_transcode, i'm currently using in sample_multi_transcode and it works like i want but smt have few options not like QSVEncc that have alot of options to encode with QSV

-VppHvsDenoise <mode> <level>
                Enables vpp hvsdenoise filter)
                    mode - mode of deniose
                        0    - default
                        1001 - auto BD rate
                        1002 - auto subjective
                        1003 - auto adjust
                        1004 - manual mode for pre-processing, need level
                        1005 - manual mode for post-processing, need level
                level - range of noise level is [0, 100]

thanks

**Comment by rigaya** [comment]
[QSVEnc 7.46](https://github.com/rigaya/QSVEnc/releases/tag/7.46) adds these extra denoise modes, and can be used like ```--vpp-denoise auto_subjective```. Please check [the link](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-denoise-int-or-param1value1param2value2) for details.

**Comment by rigaya** [comment]
I'll close this issue as the feature has been added.
