### ISSUE TITLE
max_frame_size, tile_rows

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#148]
I tried out ffmpeg the last few days and found two useful settings for AV1 encoding on Arc, it's tile_rows and max_frame_size. Possibly also tile_cols in some cases.

I tried one video and found these two settings are good (CBR 6000): 

-max_frame_size: 50000
-tile_rows 2

PSNR, SSIM, VMAF scores are better with these. Maybe it's something for QSVEnc as well.

**Comment by mikk9** [comment]
+0.4 VMAF and +0.0034 SSIM improvement with these two settings for this video. 

![example](https://github.com/rigaya/QSVEnc/assets/18703109/e112ea5d-282d-423f-827c-fd8cb75c0114)

**Comment by rigaya** [comment]
QSVEnc 7.45 adds --tile-row, --tile-col and --max-framesize.

**Comment by mikk9** [comment]
Thanks that was fast. It appears that max-framesize isn't working, no matter what size I try it makes no difference. Tile is working.

**Comment by mikk9** [comment]
I believe --max-framesize requires VBR, it makes a difference there. ffmpeg uses VBR on default.

**Comment by rigaya** [comment]
QSVEnc has --cqp default, so you need to explicitly specify --vbr along with --max-framesize.

**Comment by Feierkuula** [comment]
the --tile-col and --tile-rows seem not working with the Intel Arc, as it is reset by driver to 0, when i specify more than 0, but with ffmpeg it works with ICQ encoding mode together. Is there an workaround?
