### ISSUE TITLE
Since 7.40 --vpp-colorspace failes on intel A380

### ISSUE THREAD

**Issue by UnAnalogFG** [rigaya/QSVEnc#149]
Hi 

7.36 seems to be last working version on A380 for encoding with --vvp-colorspace "hdr2sdr=hable"
since 7.40 it fails with an initialization error on OpenCL (tested with 7.45)

--------------------------------------------------------------------------

building OpenCL source: size 30234.
options: -D TYPE=ushort -D TYPE4=ushort4 -D bit_depth=16 -D IS_OPENCL=1
source

build log of Intel(R) Arc(TM) A380 Graphics...
3:730:20: error: use of undeclared identifier 'ind'
            { -nan(ind)f, -nan(ind)f, -nan(ind)f },
                   ^
3:731:20: error: use of undeclared identifier 'ind'
            { -nan(ind)f, -nan(ind)f, -nan(ind)f },
                   ^
3:732:20: error: use of undeclared identifier 'ind'
            { -nan(ind)f, -nan(ind)f, -nan(ind)f }
                   ^
Error (clBuildProgram): build program failure.

.
.
.

colorspace: failed to load RGY_FILTER_COLORSPACE_CL(m_colorspace)
OPENCL: Error while running filter "colorspace".
Break in task OPENCL: OpenCL crushed..

--------------------------------------------------------------------------

Environment Info
Intel Media SDK API v2.09
libmfxhw64.dll : v2.09

OS : Windows 10 x64 (19045) [UTF-8]
CPU: AMD Ryzen 9 7950X 16-Core Processor [4.57GHz] (16C/32T)
RAM: Used 6044 MB, Total 65239 MB
GPU: Intel Arc A380 Graphics (128EU) 300-2450MHz (31.0.101.4369)

**Comment by rigaya** [comment]
Thank you for reporting, [QSVEnc 7.46](https://github.com/rigaya/QSVEnc/releases/tag/7.46) shall fix this issue.

**Comment by UnAnalogFG** [comment]
Thanks, works :)
