### ISSUE TITLE
No way to determine if --audio-codec aac:aac_coder=twoloop works?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#150]
Hello @rigaya 

I want to check if it is possible to include into the output window if twoloop is enabled or not.
When using `--audio-codec aac:aac_coder=twoloop` it only outputs `-> aac/stereo/128kbps`
It would be great if there would be some information as it would help to ensure that twoloop is running indeed.

Thank you

**Comment by rigaya** [comment]
Not all information are shown in the log, in order to keep the log simple. (actually, I think I already have messed it up...)

For check purpose, it can be checked with ```--log-level debug``` as below.
```
avout: Audio Encoder Param: aac, 2ch[0x03], 48.0kHz, fltp, -99 (default), 1/48000, aac_coder=twoloop
```

**Comment by quamt** [comment]
Ok. Thank you.
