### ISSUE TITLE
No warning or error when using --la-quality slow with Codec: H.265/HEVC FF ?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#151]
Hello @rigaya,

when checking the features of the arc a770, 

This is the result for h265:

Codec: H.265/HEVC FF
             CBR   VBR   AVBR  QVBR  CQP   LA    LAHRD ICQ   LAICQ VCM
RC mode       o     o     x     o     o     x     x     o     x     x
10bit depth   o     o     x     o     o     x     x     o     x     x
Hyper Mode    o     o     x     o     o     x     x     o     x     x
Interlace     x     x     x     x     o     x     x     x     x     x
VUI info      o     o     x     o     o     x     x     o     x     x
Trellis       x     x     x     x     x     x     x     x     x     x
BFrame/GopRef o     o     x     o     o     x     x     o     x     x
Adaptive_I    o     o     x     o     o     x     x     o     x     x
Adaptive_B    o     o     x     o     o     x     x     o     x     x
WeightP       o     o     x     o     o     x     x     o     x     x
WeightB       o     o     x     o     o     x     x     o     x     x
FadeDetect    o     o     x     o     o     x     x     o     x     x
B_Pyramid     o     o     x     o     o     x     x     o     x     x
 +ManyBframes o     o     x     o     o     x     x     o     x     x
PyramQPOffset x     x     x     x     o     x     x     x     x     x
ScenarioInfo  o     o     x     o     o     x     x     o     x     x
MBBRC         o     o     x     o     x     x     x     o     x     x
ExtBRC        o     o     x     x     x     x     x     x     x     x
AdaptiveRef   x     x     x     x     x     x     x     x     x     x
AdaptiveLTR   o     o     x     o     o     x     x     o     x     x
AdaptiveCQM   x     x     x     x     x     x     x     x     x     x
LA Quality    x     x     x     x     x     x     x     x     x     x
QP Min/Max    o     o     x     o     x     x     x     o     x     x
IntraRefresh  o     o     x     o     o     x     x     o     x     x
No Deblock    o     o     x     o     o     x     x     o     x     x
No GPB        o     o     x     o     o     x     x     o     x     x
Windowed BRC  x     x     x     x     x     x     x     x     x     x
PerMBQP(CQP)  x     x     x     x     x     x     x     x     x     x
DirectBiasAdj x     x     x     x     x     x     x     x     x     x
MVCostScaling x     x     x     x     x     x     x     x     x     x
SAO           o     o     x     o     o     x     x     o     x     x
Max CTU Size  o     o     x     o     o     x     x     o     x     x
TSkip         o     o     x     o     o     x     x     o     x     x

Which means that `--la-quality slow` should not work or at least provide an message that it was disabled?
However it doesn't show a warning nor error or something else.
Is that indented behaviour?
Or did I misunderstand something?

**Comment by rigaya** [comment]
```--la-quality``` only takes effect when used with ```--la```, ```--la-hrd```, ```--la-icq```. Therefore, no message will be shown when used with other rate control mode options.

**Comment by quamt** [comment]
OK.
Does that mean when I use --cqp I can not determine the --output-depth

**Comment by rigaya** [comment]
Yes, with cqp, la-depth will not take effect(will be ignored).

**Comment by quamt** [comment]
I see. 
Is there anywhere a table or similar where it can be checked which option does work with which other option?
Something like a Wiki would be nice, which might avoid repeating questions.

**Comment by rigaya** [comment]
> Is there anywhere a table or similar where it can be checked which option does work with which other option?

Unfortunately not. As QSVEnc has many options, we can think of various combinations of options, which I won’t be able to cover orlando continuously maintain a table in a limited amount of time.

**Comment by quamt** [comment]
Ok, understand. 
Does that mean it will also not show when debug is enabled?

**Comment by quamt** [comment]
Closing as completed.
