### ISSUE TITLE
Is it possible to pipe NVEnc's output into QSVEnc?

### ISSUE THREAD

**Issue by my-password-is-password** [rigaya/QSVEnc#152]
I can pipe NVEnc into ffmpeg and get valid output but when I try to do the same with QSVEnc the output is messed up.  Am I doing something wrong or is it not possible. The NVEnc command is the same for both below. For the QSVEnc one I set both ```input-res``` and ```fps``` like it said https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--raw .

### NVEnc -> ffmpeg

```NVEncC64.exe --avhw --input "INPUT.mp4" --output-res 720x576 --output-format raw --output - | ffmpeg.exe -i pipe: -c:v mpeg2video "OUTPUT.m2v"```

OUTPUT.m2v:

![mpv_0iD7n86lYK](https://github.com/rigaya/QSVEnc/assets/6408935/358ee828-c51f-4a06-a661-107e6aaa9c4c)

---

### NVEnc -> QSVEnc

```NVEncC64.exe --avhw --input "INPUT.mp4" --output-res 720x576 --output-format raw --output - | QSVEncC64.exe --raw --input-res 720x576 --fps 25/1 --input - --codec mpeg2 --output-format mpeg2video --output "OUTPUT.m2v"```

OUTPUT.m2v:

![mpv_6x8tJvU9R8](https://github.com/rigaya/QSVEnc/assets/6408935/8f256e85-2818-44a2-ab09-64da79d88f9e)

Thank you for both NVEnc and QSVEnc. 

- Windows 10
- NVEncC (x64) 7.30 (r2572) by rigaya, Jun 24 2023 02:43:35 (VC 1929/Win)
- NVENC / CUDA   NVENC API 12.1, CUDA 12.1
- QSVEncC (x64) 7.46 (r3106) by rigaya, Jun 24 2023 05:23:24 (VC 1936/Win)
- Media SDK      QuickSyncVideo (hardware encoder) PG, 2nd GPU, API v1.33
- GPU 0: NVIDIA GeForce GTX 1080
- GPU 1: Intel UHD Graphics 630 (24EU)

**Comment by rigaya** [comment]
--raw for QSVEnc is for raw (non compressed) video, and not suitable for this case. I think just removing --raw shall work.

**Comment by my-password-is-password** [comment]
You're right.  It works when I remove the --raw from the QSVEnc.  Thanks again. 👍
