### ISSUE TITLE
--vpp-subburn special characters causing error or wrong characters

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#153]
Hello,

I noticed that when the subtitles include a special character it produces an error.

Example:

`[ssa @ 0000024796254400] Unable to recode subtitle event "40,0,Default,,0,0,0,,Jeder weiß,`

This happens with all lines that contain the German special characters in that example it's the 'ß'.

Other special characters like 'ä, ö, ü' seem to get converted into different languages.
See attached screenshot:
![image](https://github.com/rigaya/QSVEnc/assets/64795789/3a6ac4cd-6988-4429-8fca-6941f223e0ad)

Is there any way to avoid or fix this?
Or does this require an update somewhere?

**Comment by rigaya** [comment]
I'm not sure of the german codes, but "charcode" options for [--vpp-subburn](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-subburn-param1value1param2value2) might work.

When input is ass file, QSVEnc tends to use CP932(Japanese) or UTF-8, for other character codes you may need to specify the target charcode.

**Comment by quamt** [comment]
Ok. 
I'll check and report back.
Thank you.

**Comment by quamt** [comment]
I added charcode=UTF-8 and it seems ok now for the mentioned characters.
I guess that charcode=ISO-8859-1 would have worked too, but did not test.
I'll close this for the moment and report back if there are any issues popping up.
Thank you.
