### ISSUE TITLE
QSVEnc and NVEnc

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#155]
will these fixes work? when will you release the update? or should it not be changed?

StaxRip v.2.21.00

![123](https://github.com/rigaya/QSVEnc/assets/95682410/896f76f9-a080-45ea-834a-be517d0320de)

**Comment by quamt** [comment]
> will these fixes work? when will you release the update? or should it not be changed?
> 
> StaxRip v.2.21.00
> 
> ![123](https://user-images.githubusercontent.com/95682410/251008487-896f76f9-a080-45ea-834a-be517d0320de.jpg)




@Discograp 
As to my knowledge StaxRip uses the the executables from @rigaya.

**Comment by Discograp** [comment]
yes, he was using your files. but in this version added fixes - are these fixes yours or his? disappear when you update?

**Comment by quamt** [comment]
``I'm not the one developing the encoders, I only saw your question and replied to it.

As for the fixes, the latest ones can be found on the official github from @rigaya.

I do not know who is responsible for StaxRip, but to my knowledge it uses external tools to achieve what it does. And some one them are from @rigaya. The QSVencC, the NVEncC and the VCEncC.
So the fixes should be from @rigaya.
You can also try to check the tools that are included in the StaxRip and run a commandline in the tool that you want to check for example QSVEncC64.exe --version and that will return similar to the example below:

```
QSVEncC (x64) 7.37 (r3038) by rigaya, Apr 12 2023 10:17:22 (VC 1934/Win)
 Intel Media SDK API v2.09
 reader: raw, avi, avs, vpy, avsw, avhw
```

**Comment by Discograp** [comment]
ok
