### ISSUE TITLE
Memory leak when using OpenCL filters on specific environments 

### ISSUE THREAD

**Issue by rigaya** [rigaya/QSVEnc#156]
There seems to be memory leak when using any OpenCL filters in specific environments, memory usage of QSVEnc continuously go up as time pass. Strangely, the problem seem to not apply to all systems.

- Tested with QSVEnc 7.46

- Example options
  QSVEncC64.exe -i input -o output --vpp-pmd apply_count=5

- systems confirmed to have memory leak
  - Win11 i9 12900K (ADL)
  - Win11 Arc A380 (DG2)

- systems confirmed to **not** have memory leak
  - Ubuntu 22.04 i3 N305 (ADL)
  - Win11 i5 1035G7 (ICL)
  - Win10 i5 7500 (KBL)

I’m currently not being able to find out the cause or ways to avoid this memory leak. It’s weird that the behavior differs between systems, even if I run the same option with same binary.

**Comment by quamt** [comment]
Does the error message look like this when it happens?

`[NULL @ 00000287705d5640] Invalid NAL unit size (22786 > 2624).U 18%, VD 96%, est out size 198.3MB
[NULL @ 00000287705d5640] missing picture in access unit with size 2639
avqsv: corrupt packet in video: 13218205 (550.759)
avqsv: failed to run h264_mp4toannexb bitstream filter: Invalid data found when processing input.
MFXDEC: Error on getting video bitstream: unknown error..
Break in task MFXDEC: unknown error..

encoded 13127 frames, 281.06 fps, 1099.77 kbps, 71.78 MB
encode time 0:00:46, CPU: 0.9%, GPU: 18.1%, VD: 96.8%
frame type IDR     1
frame type I      55,  total size   3.37 MB
frame type P     766,  total size  19.92 MB
frame type B   12306,  total size  48.49 MB


QSVEncC.exe finished with error!`

**Comment by rigaya** [comment]
No, actually there are no error message with the memory leak mentioned, it runs successfully, the only problem is the memory leak (memory usage of QSVEnc continuously goes up).

**Comment by rigaya** [comment]
Seems to have been driver issue, no issue with QSVEnc 7.53 + 4953 driver on DG2.
