### ISSUE TITLE
QSVEncC aborts after update to latest Intel graphics driver (v 31.0.101.4575)

### ISSUE THREAD

**Issue by ukmark62** [rigaya/QSVEnc#159]
Just upgraded graphics driver from Intel and now HEVC encodes are aborting with following message. I am using StaxRip tool and version 7.46v2 of QSVEnc. All works well with previous version of graphics driver (v 31.0.101.4502):-

**QSVEnc Error (v2.22.0)

H.265/HEVC isn't supported by your Hardware.

StaxRip.ErrorAbortException: H.265/HEVC isn't supported by your Hardware.
   at StaxRip.QSVEnc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\QSVEnc.vb:line 104
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 371**

Windows 11 Home
Version: 22H2
OS Build: 22621.1992
Experience: Windows Feature Experience Pack 1000.22644.1000.0
Graphics Card is 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	12.0 GB

**Comment by rigaya** [comment]
Would you please let me know the exact command line as the behavior will differ depending on the options, and the actual error message of QSVEncC for futher findings (not message from StaxRip)?

Unfortunately, I were not able to reproduce the error with following command line.

x64\QSVEncC64 -i input -o output -c hevc --vbr 6000

System
```
OS             Windows 11 x64 (22621) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [4.89GHz] (8P+8E,16C/24T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [125W] (31.0.101.4575)
Media SDK      QuickSyncVideo (hardware encoder) PG, 2nd GPU, API v2.09
```

**Comment by ukmark62** [comment]
Apologies for that. Very strange that it works when using command line for QSVEncC but not when using StaxRip GUI. 
Here is command line for QSVEncC which works:-

D:\StaxRip\Apps\Encoders\QSVEncC>QSVEncC64 -i x264.mkv -o output  --avhw --cqp 30:32:33 --qp-offset 2:4:8 --codec hevc --quality best --profile main10 --bframes 16 --b-pyramid --b-adapt --i-adapt --adapt-ltr --open-gop --async-depth 4 --no-repeat-pps --no-tskip --sao none --fixed-func --output-res 1280x640
--------------------------------------------------------------------------------
output
--------------------------------------------------------------------------------
cop.SingleSeiNalUnit value changed off -> auto by driver
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver
QSVEncC (x64) 7.46 (r3106) by rigaya, Jun 24 2023 05:23:24 (VC 1936/Win)
OS             Windows 11 x64 (22621) [UTF-8]
CPU Info       11th Gen Intel Core i5-1135G7 @ 2.40GHz [TB: 4.21GHz] (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (80EU) 100-1300MHz [28W] (31.0.101.4575)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU, API v2.09
Async Depth    4 frames
Hyper Mode     off
Buffer Memory  d3d11, 67 work buffer
Input Info     avqsv: H.264/AVC, 720x360, 24000/1001 fps
VPP            ColorFmtConvertion: nv12 -> p010
               Resize 720x360 -> 1280x640
AVSync         cfr
Output         HEVC(yuv420 10bit) main10 @ Level 4
               1280x640p 1:1 23.976fps (24000/1001fps)
Target usage   1 - best
Encode Mode    Constant QP (CQP)
CQP Value      I:30  P:32  B:33
QP Limit       min: 22, max: 63
Ref frames     6 frames
Bframes        16 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  WeightP WeightB GPB QPOffset AdaptiveLTR ctu:64 sao:none

encoded 66790 frames, 494.26 fps, 814.55 kbps, 270.50 MB
encode time 0:02:15, CPU: 3.0%, GPU: 50.7%, VD: 88.7%
frame type IDR     5
frame type I     284,  total size   12.93 MB
frame type P    3901,  total size   96.66 MB
frame type B   62610,  total size  161.08 MB

Here is the log produced by StaxRip:-
[x264_staxrip.log](https://github.com/rigaya/QSVEnc/files/12136034/x264_staxrip.log)

I think therefore this is one for the StaxRip team??

**Comment by rigaya** [comment]
I made change to avoid crush of --check-features with the new driver, --check-features will work fine even with 4575 driver at [QSVEnc 7.47](https://github.com/rigaya/QSVEnc/releases/tag/7.47).

**Comment by ukmark62** [comment]
Thanks so much rigaya! All is working fine again now with latest 4575 driver.

**Comment by rigaya** [comment]
Thank you for confirming, nice to hear it now works fine also with StaxRip.
