### ISSUE TITLE
Frame rate setting

### ISSUE THREAD

**Issue by sportniik** [rigaya/QSVEnc#160]
I hope this is not to dumb question, but how can I set output video to certain frame rate?

If I have a 50fps .ts source and want to convert it to 25fps .mp4 h.264. Is it possible? I looked at the "QSVEncC option list", but could not identify the correct setting.

Thank you!

**Comment by rigaya** [comment]
QSVEncC does not support general frame rate conversion, it only supports dropping framerate by a specific rate.

You might try "[--vpp-decimate](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-decimate-param1value1param2value2) cycle=2", for halving the framerate.

**Comment by sportniik** [comment]
😢that is sad to hear. Frame rates are really basic parameter like resolution or bitrate.
But anyway thank you for suggestion will try different combination in suggested category.
