### ISSUE TITLE
AV1 Encoding--CQP vs ICQ Mode

### ISSUE THREAD

**Issue by wwaag76** [rigaya/QSVEnc#165]
Just did some AV1 test encodes using CQP and ICQ modes with the same factor--28.
For ICQ, the resulting bit rate of the rendered file was 13 Mb/s which seems reasonable.  However, for CQP mode, the bit rate was 63 Mb/s, roughly 5 times as large and more than twice the bit rate of the original file.
Is this correct?  It would appear that CQP mode may be using 0-256 rather than 0-51.

**Comment by rigaya** [comment]
Yes, AV1 CQP range is 0 - 255.

**Comment by wwaag76** [comment]
Thanks.  One other question.  What are the correct CQP and ICQ ranges for VP9?

**Comment by iccfish** [comment]
> Thanks. One other question. What are the correct CQP and ICQ ranges for VP9?

Seems 0-51.

**Comment by Discograp** [comment]
for me

**Comment by rigaya** [comment]
I'll close this issue as the question has been answered.
