### ISSUE TITLE
vp9 encoding--changing cqp or icq value has no effect

### ISSUE THREAD

**Issue by wwaag76** [rigaya/QSVEnc#166]
I've been doing some test encoding using vp9.  Changing the cq value for either the cqp icq mode has no effecte on the bitrate of the rendered file. The bitrate in icq is extremely low, 528 kb/sec while the bitrate in cqp mode is always high at 65 mb/sec.

Here is the generic command line I'm using for icq.  
qsvencc64 -i inAVSfile  --codec vp9  --icq 20 --quality balanced --audio-source inTempWavFile:codec=aac;bitrate=128;delay=44 -o outFile.mp4

Use of bitrate modes works OK.

**Comment by rigaya** [comment]
With Intel Arc A380, VP9 --cqp did had effect on bitrate, although it didn't really go down to low bitrate. --icq had no effect as you have mentioned.

Anyway QSV VP9 has poor quality, I recommend to use H264, HEVC, or AV1.

**Comment by wwaag76** [comment]
Thanks for your reply.  I was using an Intel Arc 770.  As mentioned, bitrate modes still work OK.  Consider this closed.
