### ISSUE TITLE
AV1 Film Grain Synthesis?

### ISSUE THREAD

**Issue by writersblock73** [rigaya/QSVEnc#167]
One aspect of AV1 encoding which I've found to be indispensable is the use of film grain synthesis. While this is relatively straightforward in software encoders, I've been spoiled by the speed of my Intel Arc card. I've been adding to my gray hair trying to figure out if it's possible to do with that card--or any other hardware, for that matter. Are there plans for adding such functionality to QSVEnc? I'm starting to wonder if it's all about denoising with filters, then figuring out how to edit the resulting file to instruct the playback device to add a field of noise. If Intel already has a method "baked in," and it can be tapped into, I'd pretty much have to name a kid after you.

**Comment by rigaya** [comment]
I'm sorry, but I have no idea about film grain synthesis...

**Comment by writersblock73** [comment]
Honestly, that actually makes me feel better. Looking at (and using) your work, you've probably forgotten more about Quicksync than I'll ever know. Thanks for what you do, and I appreciate the response!
