### ISSUE TITLE
10-bit

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#168]
please fix the bug
when I select H.264 and configure it to Constant QP -Balanced -High -10bit VPP:2xFPS(BoB) + TFF + yuv420

after processing it produces 8-bit

and when I select H.265 and configure it to 10-bit, everything is fine

**Comment by rigaya** [comment]
This is not a bug, as QSV does not support H.264 10bit depth encoding.

**Comment by Discograp** [comment]
???????????????????? omg !!!!!!!!!!!!!!!!!!
