### ISSUE TITLE
--max-bitrate and icq

### ISSUE THREAD

**Issue by MrWGT** [rigaya/QSVEnc#169]
I want to limit max bitrate while using icq mode for hevc. It looks like that max-bitrate is ignored. Giving max-bitrate 20000 and 50000 results in no difference in file size and both encodes of different shows same max bitrate around 70Mbps.

Edit: Intel Arc A380

**Comment by rigaya** [comment]
Unfortunately, --icq does not support --max-bitrate.

When using --max-bitrate, it is required to use --vbr (or --cbr).
