### ISSUE TITLE
QSVEnc doesn't support VC-1 files

### ISSUE THREAD

**Issue by Patman86** [rigaya/QSVEnc#17]
Hi rigaya,

i've tested the QSVEnc hardware decoder with some mkv files based on the VC-1 codec. None of these files can be decoded with QSVEnc. The hardware is an intel HD4600 with the latest driver installed. The "--check-features" option indicates that support for vc-1 is granted.

**Comment by rigaya** [comment]
I'm sorry but I have decided to remove VC-1 hw decode support in [QSVEnc 3.25](https://github.com/rigaya/QSVEnc/releases/tag/3.25), as I found it difficult to make it work.
