### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#170]
launched StaxRip v.2.29.0

uploaded mpeg-ts tff 1080i 29.97fps 1h13m05s

set up QSV 265 main10 10-bit + VPP: 2xFPS + TFF + yuv420

then I made Trim and started processing

During processing I showed this

cop.SingleSeiNalUnit value changed off -> auto by driver
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver

after processing it turned out what I wanted. And because of whom and why are these mistakes?

my i GPU 770 = Intel Graphics Driver 31.0.101.4824 (WHQL Certified)

**Comment by rigaya** [comment]
You can ignore the message, it's just saying that the driver is adjusting the parameters for actual use.

**Comment by Discograp** [comment]
ok
