### ISSUE TITLE
autocrop function

### ISSUE THREAD

**Issue by Feierkuula** [rigaya/QSVEnc#171]
Hi,

your program is great, but i wish an function to be added into the QSVEnc.

Currently, i do automatic crop detection from ffmpeg and then passing the crop parameters to QSVEnc to remove the black bars from video files.

It would be great if the QSVEnc can do in one run instead of using ffmpeg for detecting cropping.

**Comment by rigaya** [comment]
Although I can understand that it will be easier if it can autocrop in single process, I think autocrop is better done using ffmpeg, as it is difficult to implement.

As it will be 2pass process anyway, it will not have performance advantages.

**Comment by Feierkuula** [comment]
No problem, i have been using ffmpeg too. Thanks.
