### ISSUE TITLE
[SUGGESTION] Can AVX/AVX2/AVX-512 optimizations speed up encoding ?

### ISSUE THREAD

**Issue by forart** [rigaya/QSVEnc#175]

**Comment by rigaya** [comment]
Already AVX2 is used on colorspace conversion, and AVX2/AVX512 for bitstream parsing.

AVX2/AVX512 will not help for encoding tasks on the GPU side (as it is a CPU feature).

**Comment by forart** [comment]
Sorry, the message body hasn't been posted, here it is:

Many a/v de/en-coders are introducing (even compiler-only) AVX* optimizations, here's a couple of examples:
- @ultravideo's [ugv266 v0.8.0](https://github.com/ultravideo/uvg266/releases/tag/v0.8.0);
- [RareWares](https://www.rarewares.org/)'s [FLAC v1.4.3](https://www.rarewares.org/lossless.php#flac-bundle).

Anyway thanks for the tech explaination.
