### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#177]
These levels are 6.0 6.1 6.2 with basic x264
when processing UHD content (3840*2160) they process well, without errors

please make them visible and available for QSVenc and NVenc 264

**Comment by rigaya** [comment]
H.264 [Level](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--level-string) 6, 6.1, 6.2 is already added.

```
   --level <string>             set codec level
                                - H.264: auto(default), 1, 1b, 1.1, 1.2, 1.3
                                         2, 2.1, 2.2, 3, 3.1, 3.2, 4, 4.1, 4.2
                                         5, 5.1, 5.2, 6, 6.1, 6.2
```

**Comment by Discograp** [comment]
Thanks!

**Comment by Discograp** [comment]
I must have misunderstood the translation

will these levels be available in the next release of the new versions?????

otherwise they are not available now

**Comment by rigaya** [comment]
They are already available for the app but limited by driver.

```
vidprm.mfx.CodecLevel value changed 6 -> 5.1 by driver
```

**Comment by Discograp** [comment]
your source 3840*2160 ??????
