### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by Discograp** [rigaya/QSVEnc#178]
encoding modes have changed

QSVenc, like NVenc, no longer supports Levels - only Auto-level

and these modes too - Best Higher High Balanced Fast Faster Fastest < Quality Balanced Performance and Performance from 1 to 7 as NVenc

:) you may not believe it

**Comment by rigaya** [comment]
I don't get what you mean here...

--level and --quality option works fine for all codec as far as I have tested with QSVEnc 7.51 on Win11, Arc A380 and HDG770.

**Comment by Discograp** [comment]
ok
