### ISSUE TITLE
About features and MediaSDK support on linux ubuntu 19.04

### ISSUE THREAD

**Issue by thx4ever** [rigaya/QSVEnc#18]
Hi rigaya

I tried a fresh Intel Media SDK install and compiled latest QSVEncc on linux ubuntu 19.04
compilation is fine however i cant get support for hevc encoding on Kabylake Platform, if i use MediaSDK samples are working but QSVEncc dont detect HEVC and H264 are all X
I have added my command line options

qsvencc --check-features
Checking for QSV...
QSVEncC (x64) 3.25 (r1641) by rigaya, Sep 16 2019 22:28:47 (gcc 8.3.0/Linux/avx2)
 reader: raw, avqsv [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1]
 vpp:    resize, deinterlace, denoise, detail-enhance, image-stab, delego
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
No LSB modules are available.
Environment Info
OS : Ubuntu 19.04 x64
CPU: Intel Core i7-7700 @ 3.60GHz [TB: infGHz] (4C/8T)
RAM: Used 4543 MB, Total 6909 MB
GPU: Intel Graphics / Driver : Intel iHD driver - 19.1.0.git_42f6f23_2019-04-23

No LSB modules are available.
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
libva info: va_openDriver() returns 0
Media SDK Version: Hardware API v1.30

Supported Enc features:
Codec: H.264/AVC
             CBR   VBR   AVBR  QVBR  CQP   LA    LAHRD ICQ   LAICQ VCM  
RC mode       x     x     x     x     x     x     x     x     x     x    
10bit depth   x     x     x     x     x     x     x     x     x     x    
Fixed Func    x     x     x     x     x     x     x     x     x     x    
Interlace     x     x     x     x     x     x     x     x     x     x    
VUI info      x     x     x     x     x     x     x     x     x     x    
Trellis       x     x     x     x     x     x     x     x     x     x    
Adaptive_I    x     x     x     x     x     x     x     x     x     x    
Adaptive_B    x     x     x     x     x     x     x     x     x     x    
WeightP       x     x     x     x     x     x     x     x     x     x    
WeightB       x     x     x     x     x     x     x     x     x     x    
FadeDetect    x     x     x     x     x     x     x     x     x     x    
B_Pyramid     x     x     x     x     x     x     x     x     x     x    
 +ManyBframes x     x     x     x     x     x     x     x     x     x    
PyramQPOffset x     x     x     x     x     x     x     x     x     x    
MBBRC         x     x     x     x     x     x     x     x     x     x    
ExtBRC        x     x     x     x     x     x     x     x     x     x    
Adaptive_LTR  x     x     x     x     x     x     x     x     x     x    
LA Quality    x     x     x     x     x     x     x     x     x     x    
QP Min/Max    x     x     x     x     x     x     x     x     x     x    
IntraRefresh  x     x     x     x     x     x     x     x     x     x    
No Deblock    x     x     x     x     x     x     x     x     x     x    
No GPB        x     x     x     x     x     x     x     x     x     x    
Windowed BRC  x     x     x     x     x     x     x     x     x     x    
PerMBQP(CQP)  x     x     x     x     x     x     x     x     x     x    
DirectBiasAdj x     x     x     x     x     x     x     x     x     x    
MVCostScaling x     x     x     x     x     x     x     x     x     x    
SAO           x     x     x     x     x     x     x     x     x     x    
Max CTU Size  x     x     x     x     x     x     x     x     x     x    
TSkip         x     x     x     x     x     x     x     x     x     x    

libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
Supported Vpp features:

Resize                o
Deinterlace           o
Scaling Quality       o
Denoise               o
Mctf                  o
Rotate                x
Mirror                o
Detail Enhancement    o
Proc Amp.             o
Image Stabilization   o
Video Signal Info     o
FPS Conversion        o
FPS Conversion (Adv.) o

libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
Supported Decode features:

            H.264 HEVC MPEG2 VP8  VP9  VC-1 
HW Decode      o    x    o    x    x    o 
10bit depth    x    x    x    x    x    x 

qsvencc --check-hw
Success: QuickSyncVideo (hw encoding) available

qsvencc --check-lib
QSVEncC (x64) 3.25 (r1641) by rigaya, Sep 16 2019 22:28:47 (gcc 8.3.0/Linux/avx2)
 reader: raw, avqsv [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, VC-1]
 vpp:    resize, deinterlace, denoise, detail-enhance, image-stab, delego
libmfxhw64.dll : v1.30
libmfxsw64.dll : ----

Can u try to fix it?

Regards

thx4ever

**Comment by rigaya** [comment]
I'm afraid Kabylake series does not have Media SDK support. (Please refer to the [link](https://software.intel.com/en-us/forums/intel-media-sdk/topic/721038).)

It seems like it still has VA-API support, but QSVEncC will not focus on that (it's completely different API).

**Comment by rigaya** [comment]
I'll close this issue, as the topic has been answered.
