### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by Andrasolin** [rigaya/QSVEnc#182]
Hello! Please change the "rotation":

1. Turn/Rotate 90 - to the Left
2. Turn/Rotate 90 - to the Right
3. Flip/mirror - Vertical
4. Flip/mirror - Horizontally

**Comment by rigaya** [comment]
We already have [--vpp-rotate](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-rotate-int) and [--vpp-transform](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-transform-param1value1param2value2).

**Comment by Andrasolin** [comment]
ok
