### ISSUE TITLE
I am a computer novice and I don't know why my device doesn't support la icq mode when transcoding videos

### ISSUE THREAD

**Issue by refuckable** [rigaya/QSVEnc#186]
![屏幕截图 2023-12-19 023308](https://github.com/rigaya/QSVEnc/assets/142878514/12f9b056-7df3-4be1-94ba-42fd99b83d0e)
I sent a screenshot of running the command line, which should contain all the key information

**Comment by rigaya** [comment]
Simply la-icq does not support HEVC encoding. icq is used instead and that should be fine.

**Comment by refuckable** [comment]
太谢谢了嘿嘿嘿
&nbsp;


water&nbsp;maker
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月21日(星期四) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: "water ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rigaya/QSVEnc] I am a computer novice and I don&#39;t know why my device doesn&#39;t support la icq mode when transcoding videos (Issue #186)





 
Simply la-icq does not support HEVC encoding. icq is used instead and that should be fine.
