### ISSUE TITLE
Question: CQP and --max-bitrate not compatible?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#187]
Hello @rigaya 

I want to check.

When using CQP for encoding the option --max-bitrate is not possible or better say not intended to work.

**Comment by rigaya** [comment]
Yes,  --max-bitrate is not possible to be used with CQP, if you need --max-bitrate then you shall go for other bitrate control modes.

**Comment by quamt** [comment]
Ok. 
In that case, I will use the `--qp-offset` option with CQP to limit the size.

Thank you for the clarification @rigaya 

I am closing this.
