### ISSUE TITLE
Setting average bitrate?

### ISSUE THREAD

**Issue by CraftyDlx** [rigaya/QSVEnc#189]
Using for instance `--qvbr 17000` seems to set the maximum bitrate rather than the average bitrate, so I dont see the difference to` --max-bitrate`. Running a test, `--qvbr 17000 --qvbr-q 15` as an example, does never exceed 17000 kbps during encoding. For testing, I also tried `--qvbr 17000, --qvbr-q 10 --max-bitrate 25000` but still, QSVEnc does never go higher than 17000, even while stating "Max bitrate: 25000 kbps" in CLI.

Usually, when using average bitrate mode, 17000 kbps would be exceeded sometimes during encoding to use more kbps for more complex frames and using less in simpler frames. The result would be around 17000 kbps.

Is there a way in QSVEnc to encode a video by setting a true average bitrate that works like I described?

**Comment by rigaya** [comment]
For average bitrate, first please try for ```--vbr`` mode, it should result better agreement with the bitrate set.

**Comment by CraftyDlx** [comment]
Well, at [https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#encode-mode-options](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#encode-mode-options) you say "CBR, VBR, AVBR are rather basic encoding modes, and although they are fast, the quality tends to be poor." So I'd prefer using QVBR but it seems to be broken. I did some further testing and

`--codec hevc --quality 1 --qvbr 18000 --qvbr-q 16` resulted in a file with 18800kbps, while the same source and
`--codec hevc --quality 1 --qvbr 25000 --qvbr-q 16` resulted in a file with 16700kbps, which makes absolutely no sense.

My goal is to process a bunch of video files which resulted between 12000 kbps and 30000 kbps when I was using ICQ. With QVBR I was trying to set a max bitrate at 18000 kbps, so that the resulting files will range between 12000 and 18000 kbps which would be fine. What would you recommend for QSVEnc to achieve this with very good quality?

**Comment by rigaya** [comment]
I actually prefer icq mode myself. Quality based modes like icq or qvbr tends to be controlled by quality values and not the bitrate, the bitrate is only a hint for the encoder. The actual bitrate will differ depeneding on the input file.

When target bitrate is more important like your case, then vbr mode will be the best to use.

**Comment by CraftyDlx** [comment]
Okay, thanks. Since I can't find any info in the manual, could you clarify how `--qvbr` ("hint for the encoder" as you say) is properly used? The examples above are resulting from the same source and I don't understand the resultung bitrates. I thought `--qvbr 25000` would result in a higher (or at least same) bitrate than `--qvbr 18000` but it was lower.

**Comment by rigaya** [comment]
Unfortunately not, as I don’t know the actual details of the algorithms.
I’ll close this issue as the question has been answered.
