### ISSUE TITLE
Fixed function encoding on Ice Lake i7-1065g7 laptop

### ISSUE THREAD

**Issue by ukmark62** [rigaya/QSVEnc#19]
Hi rigaya,

Many thanks for your QuickSync support!

I seek your opinion on the following issue I have. I am using StaxRip (which uses the QSVEnc app) to encode using the "fixed-function" method and bypassing the GPU execution units. I think this method uses the ASIC chip on the laptop - encode speeds are **_very_** fast (over 500fps for h264 @720p and 350fps for h265 10bit), and quality is also **_very_** good (perhaps the new Ice Lake hardware has improved a lot??). When encoding to h264, changing the ICQ (Intelligent Constant Quality) level (say from 25 to 22), works in that changing that setting affects the resulting file size/quality.  However, when encoding to h265 (using same settings), changing the ICQ level does not change the output file size.

I would have expected changing ICQ level to affect output size. It works for h264 but not for h265.

I have posted this question also on the StaxRip forum. Do you think this is an Intel issue, or is it StaxRip or a QSVEnc issue? I am using QSVEnc v3.30. Thanks.

I've posted an example of the StaxRip log below showing a quick test. 

_**UPDATE: It works for h265 and fixed-func if you set the encode method to QVBR-q or VBR. Changing the quality setting, (or bit rate for VBR), does affect the output file size. Still no joy with ICQ and h265.**_

D:\StaxRip\Apps\Encoders\QSVEnc\QSVEncC64.exe --avhw --codec hevc --quality best --profile main10 --fixed-func --icq 22 --crop 2,140,2,140 --output-res 1280x536 --trim 0:1956 -i "C:\Users\mark_\Videos\Star Trek Into Darkness.mkv" -o "C:\Users\mark_\Videos\Star Trek Into Darkness_temp\Star Trek Into Darkness_out.hevc"

---------------------------------------------------------------------------------------------

B pyramid on IvyBridge generation might cause artifacts, please check your encoded video.
vidprm.mfx.GopRefDist value changed 4 -> 1 by driver
vidprm.mfx.TimeStampCalc value changed 4 -> 1 by driver
cop2.BRefType value changed 2 -> 1 by driver
cop3.DirectBiasAdjustment value changed off -> auto by driver
cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver
QSVEncC (x64) 3.30 (r1724) by rigaya, Feb  1 2020 23:59:30 (VC 1916/Win/avx2)
OS             Windows 10 x64 (18363)
CPU Info       Intel Core i7-1065G7 @ 1.30GHz [TB: 3.89GHz] (4C/8T)
GPU Info       Intel Iris(R) Plus Graphics (64EU) 300-1100MHz [15W] (26.20.100.7755)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU, API v1.30
Async Depth    6 frames
Buffer Memory  d3d9, 1 input buffer, 30 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 24000/1001 fps
Crop           2,140,2,140 (1920x1080 -> 1916x800)
VPP Enabled    ColorFmtConvertion: nv12 -> p010
Resizer, 1920x1080 -> 1280x536
Trim           0-1956 [offset: 0]
AVSync         cfr
Output         HEVC main10 @ Level 3.1
1280x536p 1:1 23.976fps (24000/1001fps)
Target usage   1 - best
Encode Mode    ICQ (Intelligent Const. Quality)
ICQ Quality    22
QP Limit       min: none, max: none
Trellis        Auto
Ref frames     3 frames
Bframes        none
Max GOP Length 240 frames
Ext. Features  WeightP WeightB tskip ctu:64 sao:all

Start:    23:24:36
End:      23:27:08
Duration: 00:02:32

**Comment by rigaya** [comment]
I'm not sure as I haven't got chance to have IceLake gen CPUs, but there should be nothing special needed in the app to set ICQ quality rate in HEVC, so it might be something with the driver.

**Comment by ukmark62** [comment]
Thanks for checking. I doubt it will be anything to do with StaxRip, so it must be an Intel graphics driver issue. If it ever starts working, I'll let you know.
