### ISSUE TITLE
Piping to pipe:1 output fails

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/QSVEnc#190]
Hello,

I need a solution to my issue. 

Currently looks like the output from QSVEncc64 can't be anything else than a file. I should be able to pipe the output to anything else that accepts a piped input. 

My current workflow is ffmpeg piped to qsvencc as Encoder and then piping this to another tool. 

I get error when setting "-o" and "pipe:1" and I'm asked to use a real file output instead. 

pipe:1avout: failed to assume format from output filename. avout: please set proper extension for output file, or specify format using option --format. failed to initialize file reader(s).

Can you check? Thanks.

**Comment by rigaya** [comment]
Please check the documents for [--output-format](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#-f---output-format-string).

**Comment by VisionHDR** [comment]
> Please check the documents for [--output-format](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#-f---output-format-string).

The output-format document only shows a list for all supported output formats. It doesn't fix the issue.

When i pipe the output from QSVEnc to another tool, i use "-o" and "pipe:1" (since it comes from another piped ffmpeg) 
I added -output hevc , -output raw, even mpegts, doesn't make a difference. As when i set "pipe:1" as the output, it says it's invalid output format and requires an extension. 

How you would do a command o pipe the output to another tool then? I need to pipe HEVC video of course. 
In ffmpeg, you do this by piping out using "-f -mpegts -" but this didn't work for QSVEnc.

**Comment by rigaya** [comment]
Have you tried using --output-format? Below should work fine.
```
QSVEncC64.exe -i input -o - --output-format mpegts -c hevc
```
