### ISSUE TITLE
Question - Apply a filter selectively to a specific range of output frames

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#192]
Hello,

I was wondering if there's a way to apply a filter selectively to a specific range of output frames, similar to how the `--dynamic-rc` parameter functions. Your guidance on this would be greatly appreciated.

**Comment by rigaya** [comment]
Unfortunately not, filter params cannot be changed throughout the video.

Also I must say that I have no plan to add it, as it makes very complicated how to handle it as not all filters are simple 1in-1out filters.

**Comment by quamt** [comment]
Thank you for your explanation. I understand, and I will close this question now.
