### ISSUE TITLE
Question about --vpp-nlmeans fp16 parameter settings and errors

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#197]
Hello @rigaya,

I'm currently using the `--vpp-nlmeans` feature and have some questions regarding the `fp16` parameter options. While integrating this into my workflow, I’ve run into a few confusing points concerning the parameter values and their documentation.

**Documentation on `fp16 `Settings:** 
According to the documentation, the options for `fp16 `include:
`none`: Uses `fp32 `for higher precision but slower performance
`blockdiff`: Uses `fp16 `in block difference calculations for a balance between performance and precision
`fp16`: Uses `fp16 `in weight calculations for faster performance but lower precision

**Encountered Errors:** 
When I set the `fp16 `parameter using `--vpp-nlmeans fp16=fp16`, I receive the following error:

```
Error: Invalid value "fp16" for "--vpp-nlmeans fp16="
Option value should be one of below...
  auto, fp32, fp16
```

Interestingly, when I try` fp16=auto`, which the error message suggests as a valid option, I get a similar error. 
This option (auto) isn’t listed in the initial documentation.

**Confusion with Parameter Values:** 

It appears that the valid options listed in the error messages do not entirely match what’s in the documentation. 
Also, while `none ` and `blockdiff `work as expected, they are not mentioned in the error message as valid values.

Thanks a lot for your help and the awesome work on this tool!_

**Comment by rigaya** [comment]
"fp16" is written wrong and should be "all", so --vpp-nlmeans fp16=&lt;x&gt; should take "none", "blockdiff" and "all".

I'll fix the help in next release.

**Comment by rigaya** [comment]
Online document has be fixed for [--vpp-nlmeans](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.ja.md#--vpp-nlmeans-param1value1param2value2) fp16.

**Comment by quamt** [comment]
Thank you for your feedback. 
I will now mark this issue as resolved and close it.
