### ISSUE TITLE
Undocumented Parameter th_weight in --vpp-knn

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#198]
Hello @rigaya,

I’ve been using the `--vpp-knn` filter for noise reduction and I’ve noticed something potentially missing from the documentation.

While adjusting various settings and observing the output, I came across the` th_weight` parameter appearing in the output logs, like so:

`denoise(knn): radius 5, strength 0.30, lerp 0.50, th_weight 0.01, th_lerp 0.80`

However, I couldn’t find any mention of `th_weight` in the existing documentation. 
It appears alongside other parameters which are documented, such as `radius`, `strength`, `lerp`, and `th_lerp`.

Could you help clarify what `th_weight `does? 
Also, is it something that should be included in the documentation for clarity?

Thank you.

**Comment by rigaya** [comment]
th_weight is sub paramater of th_lerp, which is a cut-off threshold which weight is taken into accout for th_lerp. Larger th_weight is effectively same as larger th_lerp. Default value has minimum effect.

I don't think it is worth changing it, changing th_lerp shall be enough, but is left for my test purpose.

**Comment by quamt** [comment]
Thank you for explaining. I will close this issue.
