### ISSUE TITLE
QSVEnc 2.62 GUI?

### ISSUE THREAD

**Issue by taiziccf** [rigaya/QSVEnc#2]
Hi Rigaya,

Good days, sorry i dont speak Japanese  but i am interested with the encoder you did. i wish to try the QSVEnc 2.62 with 10bit, but i cannot find any gui that support it. could you tell me which GUI you are using?

particulary
http://blog-imgs-98.fc2.com/r/i/g/rigaya34589/qsvencc_kabylake_hevc_10bit.png

thank you!

**Comment by rigaya** [comment]
The image you have mentioned is from the plugin "QSVEnc.auo" for Japanese video editing software called "[Aviutl](http://spring-fragrance.mints.ne.jp/aviutl/)". However, for non-Japanese users, I only offer a CUI program, QSVEncC.

Fortunately, some software (not by me) supports QSVEncC as a front-end, please have a look.
- [StaxRip](https://github.com/stax76/staxrip)
  - [test build](https://github.com/stax76/staxrip/blob/master/md/test-build.md) version might support 10bit HEVC encoding.
- [Hybrid](http://www.selur.de/)
