### ISSUE TITLE
Feature Request: Advanced Colour Correction

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#203]
@rigaya,

Could you add an advanced colour correction feature? 
While the current `--vpp-tweak` and `--vpp-curves` commands are helpful, they do not offer the same precision and control as advanced colour correction.

The current `--vpp-tweak` command allows basic adjustments to brightness, contrast, gamma, saturation, and hue. 
However, it cannot independently adjust offsets and gains for individual RGB channels. 
Although powerful, the `--vpp-curves` command can be complex and less intuitive for many users who prefer straightforward adjustments for colour correction.

An advanced colour correction feature would provide the following benefits:

**_1. **Precision**: Independent control over RGB channel offsets and gains for more precise colour adjustments.
2. **Independent Channel Control**: Ability to correct specific colour imbalances without affecting the entire image.
3. **Enhanced Flexibility**: Detailed and fine-tuned colour corrections can be achieved, offering greater flexibility in achieving desired visual effects.
4. **Incremental Adjustments**: Control in increments of 1 with a range of +/-256 allows for very fine-grained adjustments, which is crucial for achieving professional-grade results._**

For reference, here are the parameters from AviUtl's advanced colour correction panel, which demonstrates the level of control that would greatly benefit QSVEnc users:

```
- Y(offs)
- Y(gain)
- Cb(offs)
- Cb(gain)
- Cr(offs)
- Cr(gain)
- R(offs)
- R(gain)
- R(gamm)
- G(offs)
- G(gain)
- G(gamm)
- B(offs)
- B(gain)
- B(gamm)
```

These adjustments are made in increments of 1 and have a range of +/-256, which allows for precise and detailed colour correction. Implementing similar parameters in QSVEnc could significantly enhance its utility for users requiring detailed colour correction capabilities.

I understand you are extremely busy, and you do not need to worry about implementing this feature. Please take the necessary time to consider this request. I understand if integrating this feature is not feasible due to technical limitations or other constraints. I truly appreciate all the hard work you put into developing and maintaining QSVEnc.

Thank you,
quamt

**Comment by rigaya** [comment]
[QSVEnc 7.68](https://github.com/rigaya/QSVEnc/releases/tag/7.68) adds support for per channel color tweak to [--vpp-tweak](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-tweak-param1value1param2value2).

Please note that the parameter range is not +/-256 but using float, to be consistent with previous vpp-tweak parameters.

**Comment by quamt** [comment]
I appreciate you implementing the per-channel color tweak. 
I will test it in the next few days and report back. 
Thank you very much.

**Comment by quamt** [comment]
It looks all good so far.
I will close this. 
If I should encounter any issues, I will open a new one.
Thank you again for your hard work.
