### ISSUE TITLE
 CQP Value does not appear to scale correctly with large input videos

### ISSUE THREAD

**Issue by Kim2091** [rigaya/QSVEnc#205]
When re-encoding large videos, CQP does not appear to scale properly past a certain point.

For example, with a 1.6 GB FFV1 lossless video, I attempted to re-encode it down to 25 MB. Doing so is impossible with CQP in your encoder.

Setting CQP 21 or CQP 48 does not matter, as it yields nearly the exact same video size and quality (of about 480 MB). I cannot get it lower. Switching to VBR does allow it to function properly however.

This is the counterpart issue to https://github.com/rigaya/NVEnc/issues/597

**Comment by rigaya** [comment]
Unfortuantely, I’m not able to find problem with CQP.

I've tested below in bat file, and scales perfectly well.

for %%i in (10 15 20 25 30 35 40 45 50) do QSVEncC64.exe -i input.mp4 -o test_%%i.mp4 --log test_%%i.log --cqp %%i

OS             Windows 11 x64 (22631) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [5.00GHz] (8P+8E,16C/24T) <DG2>
GPU Info       Intel Arc A380 Graphics (128EU) 300-2450MHz (31.0.101.5448)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU(d), API v2.10

![image](https://github.com/rigaya/QSVEnc/assets/815947/52baacfe-5164-4be3-a86f-1f0f7b9c2738)

**Comment by Kim2091** [comment]
And the same thing with this issue. I have no idea what was happening before when I opened these issues. I just re-tested and everything is fine. Sorry to have bothered you

**Comment by rigaya** [comment]
Never mind, thank you for your update and closing the issue.
