### ISSUE TITLE
AV1 UHD HDR10, not possible to encode on Intel ARC?

### ISSUE THREAD

**Issue by VisionHDR** [rigaya/QSVEnc#208]
Hello,

I'm experiencing some issues on Intel ARC Mobile (Asus ZenBook 14 2024) this laptop is able to encode same as desktop Intel ARC's any AV1 command (as far as i know). 

I was able to encode perfectly fine a UHD HDR10 with ffmpeg's qsv_av1, so I'm wondering why this isn't possible with QSVencC64 using similar/same settings?

What are the settings to use to encode a video to proper HDR10 with QSVEncC64? when i try to add a --colormatrix --transfer --colorspace to HDR10 specs i get error.

Even with a minimal command just setting the colormatrix to bt2020nc without the transfer, colorspace and metadata, like this:

QSVEncC64.exe --avsw -i "C:\AV1_testing\ProRes_4444XQ_HDR10.mkv" -o AV1_output_test.mkv --codec av1 --profile high (or main) --colormatrix bt2020nc
--------------------------------------------------------------------------------
output_av1.mkv
--------------------------------------------------------------------------------
MFXENCODE:   Failed to get required buffer size for MFXENCODE: invalid video parameters.
allocD3D11: QSVAllocator: Failed CheckRequestType: undeveloped feature.
INPUT: allocWorkSurfaces:   Failed to allocate frames: undeveloped feature..
AllocFrames:   Failed to allocate frames for INPUT-MFXENCODE: undeveloped feature..

QSVEncC.exe finished with error!

----

Is AV1 currently working for HDR encoding in QSVEncC64? Thanks.

**Comment by rigaya** [comment]
--colormatrix --transfer --colorspace does work with AV1 encoding on my system with Arc A380, when input is HEVC HDR10.

However I have never tested ProRes 4444XQ HDR10 so that might be causing error. Will it be possible to have a small test sample file which contains ProRes 4444XQ HDR10 format?

**Comment by VisionHDR** [comment]
> --colormatrix --transfer --colorspace does work with AV1 encoding on my system with Arc A380, when input is HEVC HDR10.
> 
> However I have never tested ProRes 4444XQ HDR10 so that might be causing error. Will it be possible to have a small test sample file which contains ProRes 4444XQ HDR10 format?

Hello, sure you can get a sample ProRes 4444XQ HDR10 here:
https://drive.google.com/file/d/1Zq0QLw5VgyQASBJ6VzBQNC8w0Pyy3lqu/view?usp=drive_link

Please ask access with a gmail account (i will only accept yours)

Thanks.

**Comment by rigaya** [comment]
Thank you for the sample file, I have requested access from rigaya34589 mail account.

QSVEnc should also work with --avsw, but there might be something wrong handling YUV444 12bit.

**Comment by rigaya** [comment]
Thank you for the file. By removing ```--profile high```, you shall be able to encode fine.

x64\QSVEncC64.exe -i Y:\Encoders\forest_hdr10.mkv -o F:\temp\test.mp4 -c av1 --output-depth 10 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084
```
--------------------------------------------------------------------------------
F:\temp\test.mp4
--------------------------------------------------------------------------------
cop.AUDelimiter value changed off -> auto by driver
cop.PicTimingSEI value changed off -> auto by driver
cop.SingleSeiNalUnit value changed off -> auto by driver
QSVEncC (x64) 7.68 (r3391) by rigaya, Jul 17 2024 10:25:02 (VC 1940/Win)
OS             Windows 11 x64 (22631) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [4.92GHz] (8P+8E,16C/24T) <DG2>
GPU Info       Intel Arc A380 Graphics (128EU) 300-2450MHz (31.0.101.5593)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU(d), API v2.11
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 17 work buffer
Input Info     avsw: prores(yuv444(12bit))->p010 [AVX2], 3840x2160, 25/1 fps
AVSync         auto
Output         AV1(yuv420 10bit) main @ Level 5
               3840x2160p 1:1 25.000fps (25/1fps)
               avwriter: av1 => mp4
Target usage   4 - balanced
Encode Mode    ICQ (Intelligent Const. Quality)
ICQ Quality    23
QP Limit       min: 1, max: 255
Ref frames     4 frames
GopRefDist     8, B-pyramid: on
Max GOP Length 250 frames
VUI            matrix:bt2020nc,colorprim:bt2020,transfer:smpte2084

encoded 238 frames, 58.88 fps, 11572.28 kbps, 13.13 MB
encode time 0:00:04, CPU: 4.9%, GPU: 54.0%, VD: 42.8%
frame type IDR   1
frame type I     1,  total size   0.64 MB
frame type P   237,  total size  12.49 MB
```

**Comment by rigaya** [comment]
I'll close this issue, as the solution has been presented.
