### ISSUE TITLE
Interpolation support like RIFE

### ISSUE THREAD

**Issue by LukaszBrzyszkiewicz** [rigaya/QSVEnc#209]
Hi - do you plan to add interpolation AI based solution like RIFE or you can suggest how I could use RIFE wrapper for vaporsynth?

Probably only last thing missing in QSVEnc :)

**Comment by rigaya** [comment]
Unfortunately no plans yet to add RIFE for QSVEnc, I think using vapoursynth filters like [vs-rife](https://github.com/HolyWu/vs-rife) will be realistic way.

**Comment by LukaszBrzyszkiewicz** [comment]
OK, thank you for info.

I'm doing this with AVS RIFE plugin.
