### ISSUE TITLE
Help printed by QSVEncC64.exe --help not in sync with QSVEncC_Options.en.md

### ISSUE THREAD

**Issue by stax76** [rigaya/QSVEnc#21]
We use a tool to check if StaxRip is up to date, `QSVEncC64.exe --help` does not contain:

--chromaloc
--colormatrix
--colorprim
--fullrange
--transfer
--videoformat

The file QSVEncC_Options.en.md does still contain those switches.

**Comment by rigaya** [comment]
Thank you for pointing out the missing options in --help, were added in [QSVEnc 3.32](https://github.com/rigaya/QSVEnc/releases/tag/3.32).

**Comment by stax76** [comment]
Thanks
