### ISSUE TITLE
Bitrate (VBR)

### ISSUE THREAD

**Issue by Andrasolin** [rigaya/QSVEnc#214]
StaxRip 2417
Qsvenc 769

weird situation
when selecting codec 265, this VBR-1 mode works, and when choosing 264, it ignores the specified bitrate and uses the default bitrate

With codec 264, only VBR-2 works
With codec 265 both VBR-1/2 work

![111111](https://github.com/user-attachments/assets/74276734-e705-44b7-bdb3-c014879cbd2c)

**Comment by quamt** [comment]
To my understanding, it seems that HRD (Hypothetical Reference Decoder) might be the reason why the specified bitrate is being ignored in H.264, while it works fine with H.265. 

How HRD Works (As I Understand It):
HRD ensures that the encoded video stream follows specific buffer and timing rules, which are crucial for smooth playback on hardware decoders. For H.264, these rules tend to be stricter compared to H.265 (HEVC), and if the bitrate you set doesn't fit within the HRD constraints, the encoder might override it and use a default value to stay compliant with the HRD model.

Why This Could Be Happening:
In the case of H.264, HRD could be forcing the encoder to ignore your custom bitrate and choose a safer default that works with the decoder's buffer. H.265 is more flexible with how it handles bitrate and buffer management, which is probably why the VBR mode works as expected with that codec.

Maybe @rigaya can provide more info and if my understanding is correct of that.

**Comment by Andrasolin** [comment]
What is there to understand?

codec 264 ignores the specified bitrate

**Comment by quamt** [comment]
It seems that the initial information provided wasn’t quite enough to fully understand the issue, which may have led to some confusion. To ensure accurate troubleshooting and resolve the problem efficiently, it's always helpful to provide as much detailed information as possible. This not only avoids misunderstandings but also helps in seeing clearly what might be happening. 

For a more accurate diagnosis, please share the following details:

1. System Information: 
   - It is important to know the exact GPU model and the driver version being used.
   - Also, knowing the Windows version you're running will be helpful.

2. QSVEnc Hardware and Feature Information: 
   - Please run the following commands in the folder where `qsvenc.exe` is located (open a Windows Command Prompt and navigate to that folder):
     - `qsvenc.exe --check-hw`
     - `qsvenc.exe --check-features`
Please adjust accordingly to the qsvenc name in that folder.

Share the output of these commands, as they will provide important details about the hardware capabilities and features of the GPU.

3. StaxRip Command Line: 
   - StaxRip generates a specific command line for every encode. The full command line is necessary to see exactly how the settings are being passed to QSVEnc.
   - Please share the full command line from StaxRip for the encoding process where this issue occurs.

Providing this information will help in identifying the issue faster and more efficiently. However, if you're not happy with this response, you are welcome to wait for @rigaya ’s input on the matter as well.

**Comment by rigaya** [comment]
--avbr is rather old feature, and it seems to work fine only in old environments with old drivers. For recent environmemts with newer drivers, it is recommended to simply switch to other modes, such as --vbr, --la, --la-hrd, as the problem with --avbr cannot be fixed.

For example, we can get --avbr working fine with Haswell CPUs (4th Gen Core CPUs).

```
QSVEncC (x64) 7.69 (r3433) by rigaya, Sep  4 2024 09:07:10 (VC 1941/Win)
OS             Windows 10 x64 (19045) [UTF-8]
CPU Info       Intel Core i3-4170 @ 3.70GHz (2C/4T) <Haswell>
GPU Info       Intel HD Graphics 4400 (12EU) 200-1500MHz [54W] (20.19.15.5107)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU(i), API v1.20
```

Although it tends to get rather low bitrate than specified, the bitrate is still close to what is specified.

```
--avbr 4000 -> encoded 3501 frames, 85.97 fps, 3664.32 kbps, 50.98 MB
--avbr 6000 -> encoded 3501 frames, 88.68 fps, 5498.82 kbps, 76.50 MB
```

But you cannot get this at least after Skylake as long as I have tested, I get way small bitrate whatever I set as you have said suing the same QSVEnc 7.69.

I don't think this can be fixed from the application(QSVEnc) side. As written previously, please simply switch to other modes, such as --vbr, --la, --la-hrd.

**Comment by Andrasolin** [comment]
ОК
