### ISSUE TITLE
Error using --vpp-resize mfx_ai_superres in QSVEncC 7.71 & 7.70

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#217]
Description:
While attempting to use the `--vpp-resize mfx_ai_superres` option in QSVEncC 7.71 and 7.70, the encoding process fails with an error. This issue appears to be related to buffer allocation and AI-based super-resolution in Intel’s Media SDK.

Environment:

**QSVEncC Version:** QSVEncC (x64) 7.71 (r3471) by rigaya, Oct 27 2024 12:02:14 (VC 1941/Win)
**Operating System:** Windows 11 x64 (build 22631), UTF-8
**CPU:** Intel Core i5-13600 [4.92GHz] (6P+8E, 14C/20T)
**GPU:** Intel Arc A770 Graphics (512EU), driver version 32.0.101.6127
**Media SDK:** QuickSyncVideo (hardware encoder) FF, 1st GPU(d), API v2.13

```
MFXVPP:   Failed to get required buffer size for MFXVPP: undeveloped feature.
allocD3D11: QSVAllocator: Failed CheckRequestType: undeveloped feature.
INPUT: allocWorkSurfaces:   Failed to allocate frames: undeveloped feature.
AllocFrames:   Failed to allocate frames for INPUT-MFXVPP: undeveloped feature.
avout: failed to write header for output file: Invalid data found when processing input

QSVEncC.exe finished with error!
```

```
--avhw
--cqp 32:34:36
--output-res -2x1080
--codec hevc
--output-depth 10
--bframes 16
--vpp-resize mfx_ai_superres
--audio-copy
--chapter-copy
```

**Additional Information:**

Since installing the latest Intel GPU driver (32.0.101.6127), this issue has started occurring, affecting both QSVEncC versions 7.71 and 7.70.
The error only occurs when using the `--output-depth 10` option; removing this option allows the encoding to proceed without issues.
The issue might be related to compatibility between 10-bit output depth, the AI super-resolution feature, and the latest Media SDK or Intel Arc drivers.

**Comment by rigaya** [comment]
In [the previous conversation](https://github.com/rigaya/QSVEnc/issues/212#issuecomment-2367153870), there was information that the input and output of VPP for AI super resolution is NV12. 

10bit depth requires P010(10bit/16bit) format instead of NV12 (8bit). Although I actually haven't tested 10bit in older drivers, I think it can be thought as limitation of AI super-resolution.

**Comment by quamt** [comment]
> In [the previous conversation](https://github.com/rigaya/QSVEnc/issues/212#issuecomment-2367153870), there was information that the input and output of VPP for AI super resolution is NV12.
> 
> 10bit depth requires P010(10bit/16bit) format instead of NV12 (8bit). Although I actually haven't tested 10bit in older drivers, I think it can be thought as limitation of AI super-resolution.

Thanks for the info. 
Strangely, `--vpp-resize mfx_ai_superres` with `--output-depth 10` worked fine before the latest driver update (32.0.101.6127). 
I try to roll back.

**Comment by quamt** [comment]
I rolled back to the older driver version 32.0.101.5978, and I tested both QSVEncC versions 7.70 and 7.71. Here are the outputs:

**QSVEncC 7.70 (with driver 32.0.101.5978)**
```
QSVEncC (x64) 7.70 (r3442) by rigaya, Sep 24 2024 12:52:40 (VC 1941/Win)
OS             Windows 11 x64 (22631) [UTF-8]
CPU Info       13th Gen Intel Core i5-13600 [4.71GHz] (6P+8E,14C/20T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [65W] (32.0.101.5978)
Media SDK      QuickSyncVideo (hardware encoder) FF, 3rd GPU(i), API v2.12
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 51 work buffer
Input Info     avqsv: H.265/HEVC, 1280x720, 24000/1001 fps
VPP            Resize 1280x720 -> 1920x1080, unknown, auto
AVSync         auto
Output         H.265/HEVC(yuv420 10bit) main10 @ Level 5 (high tier)
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, eac3 => matroska
Target usage   4 - balanced
Encode Mode    Constant QP (CQP)
CQP Value      I:32  P:34  B:36
QP Limit       min: 22, max: 63
Ref frames     6 frames
Bframes        16 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  WeightP WeightB GPB QPOffset tskip ctu:64 sao:all
```

**QSVEncC 7.71 (with driver 32.0.101.5978)**
```
QSVEncC (x64) 7.71 (r3471) by rigaya, Oct 27 2024 12:02:14 (VC 1941/Win)
OS             Windows 11 x64 (22631) [UTF-8]
CPU Info       13th Gen Intel Core i5-13600 [4.92GHz] (6P+8E,14C/20T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [65W] (32.0.101.5978)
Media SDK      QuickSyncVideo (hardware encoder) FF, 3rd GPU(i), API v2.12
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 51 work buffer
Input Info     avqsv: H.265/HEVC, 1280x720, 24000/1001 fps
VPP            Resize 1280x720 -> 1920x1080, unknown, auto
AVSync         auto
Output         H.265/HEVC(yuv420 10bit) main10 @ Level 5 (high tier)
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, eac3 => matroska
Target usage   4 - balanced
Encode Mode    Constant QP (CQP)
CQP Value      I:32  P:34  B:36
QP Limit       min: 22, max: 63
Ref frames     6 frames
Bframes        16 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  WeightP WeightB GPB QPOffset tskip ctu:64 sao:all
QSVEncC (x64) 7.71 (r3471) by rigaya, Oct 27 2024 12:02:14 (VC 1941/Win)
OS             Windows 11 x64 (22631) [UTF-8]
CPU Info       13th Gen Intel Core i5-13600 [4.92GHz] (6P+8E,14C/20T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [65W] (32.0.101.5978)
Media SDK      QuickSyncVideo (hardware encoder) FF, 3rd GPU(i), API v2.12
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 51 work buffer
Input Info     avqsv: H.265/HEVC, 1280x720, 24000/1001 fps
VPP            Resize 1280x720 -> 1920x1080, unknown, auto
AVSync         auto
Output         H.265/HEVC(yuv420 10bit) main10 @ Level 5 (high tier)
               1920x1080p 1:1 23.976fps (24000/1001fps)
               avwriter: hevc, eac3 => matroska
Target usage   4 - balanced
Encode Mode    Constant QP (CQP)
CQP Value      I:32  P:34  B:36
QP Limit       min: 22, max: 63
Ref frames     6 frames
Bframes        16 frames, B-pyramid: on
Max GOP Length 240 frames
Ext. Features  WeightP WeightB GPB QPOffset tskip ctu:64 sao:all



```


With this older driver (32.0.101.5978), versions 7.70 and 7.71 work OK with `--vpp-resize mfx_ai_superres `and `--output-depth 10`. The issue seems indeed linked to the latest driver update (32.0.101.6127).

**Comment by quamt** [comment]
I'm closing this.
I will be using another upscaler.
The driver's fallback did not help. 

Thank you@rigaya for checking :-)

**Comment by iori2333** [comment]
I'm on 32.101.6078 and this driver doesn't help as well.
