### ISSUE TITLE
mfx ai superres not working in Intel dGPU(A380)

### ISSUE THREAD

**Issue by scweeny** [rigaya/QSVEnc#218]
I tried it with a 60-second test video, but I'm getting the error log below.

==================================

E:\C\Downloads\QSVEncC_7.71_x64>QSVEncC64.exe -i test.mp4 -o result.mp4 --output-res 3840x2160 --vpp-resize mfx_ai_superres
--------------------------------------------------------------------------------
result.mp4
--------------------------------------------------------------------------------
QSVEncC (x64) 7.71 (r3471) by rigaya, Oct 27 2024 12:02:14 (VC 1941/Win)
OS             Windows 11 x64 (26100) [UTF-8]
CPU Info       AMD Ryzen 5 9600X 6-Core Processor [5.57GHz] (6C/12T) <DG2>
GPU Info       Intel Arc A380 Graphics (128EU) 300-2450MHz (32.0.101.6129)
Media SDK      QuickSyncVideo (hardware encoder) FF, 1st GPU(d), API v2.13
Async Depth    3 frames
Hyper Mode     off
Buffer Memory  d3d11, 33 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 30/1 fps
VPP            AI SuperRes, mode 1
               Resize 1920x1080 -> 3840x2160
AVSync         auto
Output         H.264/AVC(yuv420) High @ Level 5.1
               3840x2160p 1:1 30.000fps (30/1fps)
               avwriter: h264 => mp4
Target usage   4 - balanced
Encode Mode    ICQ (Intelligent Const. Quality)
ICQ Quality    23
QP Limit       min: none, max: none
Ref frames     3 frames
Bframes        3 frames, B-pyramid: on
Max GOP Length 300 frames
Ext. Features  PerMBRC RepeatPPS
Break in task MFXVPP: gpu hang..

encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
encode time 0:01:00, CPULoad: 0.1%

QSVEncC.exe finished with error!

=======================================

**Comment by rigaya** [comment]
Yes, it seems like scaling more than 1080p causes the GPU hang error.

It shall work fine with SD → HD, but not with HD→4K. Please use other scaler for that.

**Comment by rigaya** [comment]
I'll close the issue as the topic has been answered.
