### ISSUE TITLE
Is --input-thread still supported in QSVEnc?

### ISSUE THREAD

**Issue by stax76** [rigaya/QSVEnc#22]
Hello rigaya,

is `--input-thread` still supported in QSVEnc? It's found in the online help but not in the console help.

StaxRip includes 200 tools and it's sometimes difficult to test all tools. It would help staxrip maintenance a lot if you had a test to detect such issues, I've tests for all your tools and many other tools like x265 and constantly find issues which leads to many issues with staxrip.

https://github.com/staxrip/staxrip/blob/master/General/Test.vb

**Comment by rigaya** [comment]
It's still there, but you need not use it.

I added ```--input-thread``` because I thought it might improve performance, but unfortunately in most cases there are no performance improvement. It's left there just for test purpose. I'll remove the description from the online help.

**Comment by stax76** [comment]
OK, I've removed it from staxrip.
