### ISSUE TITLE
742

### ISSUE THREAD

**Issue by Andrasolin** [rigaya/QSVEnc#220]
Is it normal that there is no replacement? leave it or delete it?

![изображение](https://github.com/user-attachments/assets/f781866e-92a2-4a67-a299-5ee06e5de462)

**Comment by rigaya** [comment]
You mean about hdr10lus_gen?

As in the release note, 

> Changed to use [libhdr10plus](https://github.com/quietvoid/hdr10plus_tool) instead of hdr10plus_gen.exe.

hdr10lus_gen is not required anymore (the feature included in QSVEncC64 itself). It can be removed now with QSVEnc 7.72.

**Comment by Andrasolin** [comment]
aaa, ok
