### ISSUE TITLE
[REQ] Lensfun (hw-accelerated ?) filter support

### ISSUE THREAD

**Issue by MarcoRavich** [rigaya/QSVEnc#221]
Hi there,
I recently discovered the cool [Lensfun library](https://lensfun.github.io/) and the relative [FFMPEG filter](https://ffmpeg.org/ffmpeg-filters.html#lensfun).

HW-accelerated [lens correction](https://ffmpeg.org/ffmpeg-filters.html#toc-lenscorrection) would be great.

EDIT: from this interesting - even if dated (2010) - [paper on the subject](https://faculty.e-ce.uth.gr/cda/docs/ipdps10.pdf)
_In macroscopic terms, we find that todays mainstream conventional multicores are not effective in supporting real-time distortion correction, at least not with the currently commercially available core counts_ [..]
_At the same time, hardware accelerators - such as FPGAs, GPUs, or non-conventional multicore architectures such as the Cell BE - are often used to improve performance of computationally demanding algorithms or applications with execution time constraints._

**Comment by rigaya** [comment]
Unfortunately, Lensfun does not seems to provide GPU accelerated implementation, so it would be difficult to integrate it to QSVEnc.

I'm sorry but currently I have no plan to implement it to QSVEnc.
