### ISSUE TITLE
--quality setting "Balanced" and "High"

### ISSUE THREAD

**Issue by rafmib** [rigaya/QSVEnc#23]
I'm doing some tests with StaxRip/QSVEnc.
Selecting --quality "Balanced" or "High" gives exactelly the same results. (tested with StaxRip/QSVEnc 3.33 & 4.00). 
Perhaps "High" isn't working ?

**Comment by rigaya** [comment]
--quality option has **maximum** of 7 levels, which are best, higher, high, balanced, fast, faster, fastest.

However, there are not always 7 levels available, and it depends on the iGPU generation you have and also the driver version installed. For example, the first generation QSV (which was SandyBridge) had only 3 levels, best, balanced, and fastest. The latest QSV may have all 7 levels, but I'm not sure.

Therefore, it's not surprising that you get same result from high and balanced.

**Comment by rafmib** [comment]
Oh ok, i'm testing on a brand new Dell XPS 13 with Core I7-1065G7 that is the latest generation available. IGPU is Intel Iris Plus rev 07 with driver 26.20.100.7637 (latest available)

So it means "high" isn't available yet, too bad it could be a good compromise quality / encoding time.
Do you know where i can dound the info of which levels are available ?

I'm very suprised with the hardware encoding quality with QSVEnc. We're getting closer and closer to software x265 encoding :)

**Comment by rigaya** [comment]
Sorry for late response.

The warning is showing the answer to this issue.
```
vidprm.mfx.TargetUsage value changed 3 -> 4 by driver
```

The driver has not accepted TargetUsage: "3 - high", but decided to use "4 - balanced" instead. (This is checking whether the driver has changed the parameters)

I also tested these on i5 1035G7, but it seems like there are only 3 levels for HEVC encoding, even on IceLake.
- 1 - best
- 4 - balanced
- 7 - fastest

We have all 7 target usages on H.264 encoding, so it seems to be a limitation of HEVC encoding.

**Comment by rafmib** [comment]
Thank you for you reply.

So you mean this is a hardware limitation or in the future it might change even on IceLake ?

**Comment by rigaya** [comment]
> So you mean this is a hardware limitation or in the future it might change even on IceLake ?

I can't say whether it's a hardware limitation or a driver limitation (there is no way to know), but if it's a driver limitation, there might be a chance in the future driver update.

**Comment by rigaya** [comment]
I'll close this issue as this topic has been answered.
