### ISSUE TITLE
Presets? 

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#24]
I noticed that NVENC and VCEencC have presets but not QSVenc.
Is this not possible with QSV?

**Comment by rigaya** [comment]
I hope [--quality](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#-u---quality-string) might help you.

**Comment by quamt** [comment]
@rigaya 
Yes that sure is a good option.
I was curious if presets or the way presets and their settings are done, are not possible in QSV.

**Comment by rigaya** [comment]
--quality is the same meaning as the --preset in other encoders.
