### ISSUE TITLE
online docs for --profile different from console docs (online describes main444)

### ISSUE THREAD

**Issue by stax76** [rigaya/QSVEnc#25]
Was the main444 profile removed?

It's still in the online docs:

https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--profile-string

https://github.com/staxrip/staxrip/issues/234

**Comment by rigaya** [comment]
QSVEnc does not support main444 profile, the behavior of the app is correct. I will remove it from the online docs.

**Comment by stax76** [comment]
I've changed staxrip accordingly, thanks.
