### ISSUE TITLE
VP9 encoding support is available from Kaby Lake processors. Can you add a vp9 encoder?

### ISSUE THREAD

**Issue by Cuberlain** [rigaya/QSVEnc#26]
Hello Rigaya!

VP9 encoding support is available from Kaby Lake processors. Can you add a vp9 encoder?

https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding

Thank you!

**Comment by rigaya** [comment]
I'll close this issue, as VP9 support has been added.
