### ISSUE TITLE
Media SDK 2020 R1

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#27]
Intel posted a new Media SDK wich includes API 1.32.  

> The Intel Media SDK 2020 R1 introduces API version 1.32. This version is backward compatible with the previous version.
> 
> Added Screen Content Coding (SCC) support to HEVC
> Improved samples now include:
>         AVBR, QVBR, and ICQ bitrate control modes to sample_multi_transcode
>         Improved 12-bit format support
>         A command line option that forces use of a fixed function (low-power) version of components, where available
>         ROI file format for sample_multi_transcode
>         A command line option to limit bitrate
>         A metrics monitor that allows a user to specify a path to a graphics device

**Comment by rigaya** [comment]
Now [QSVEnc 4.05](https://github.com/rigaya/QSVEnc/releases/tag/4.05) is based on Media SDK 2020 R1. It mostly adds features for future gen GPUs, so I'm not adding those to the app yet.

**Comment by mikk9** [comment]
Ok thanks for the update, I will try it out. One question, are you planning to get a Tigerlake-U based Notebook with Gen12 LP graphics this year? It's coming very soon.

**Comment by rigaya** [comment]
> One question, are you planning to get a Tigerlake-U based Notebook with Gen12 LP graphics this year? 

No, I don't need notebook/laptops.

**Comment by rigaya** [comment]
I'll close this issue as Media SDK 2020 R1 has already been supported.
