### ISSUE TITLE
v4.04 crashing when using --chromaloc

### ISSUE THREAD

**Issue by hyllm** [rigaya/QSVEnc#28]
QSVenc 4.04 is crashing on i5-10400 (Comet Lake)..

i am trying to use --chromaloc 2

complete command
`QSVEncC64.exe --avsw --codec hevc --quality best --profile main10 --level 5.1 --bframes 16 --ref 5 --b-pyramid --mbbrc --weightb --weightp --master-display copy --aud -max-cll copy --colormtarix auto --colorprim auto --transfer auto --chromaloc auto --colorrange auto --aud --no-deblock --icq 16`

error:
Failed to get required buffer size for encoder. : invalid video parameters.
QSVEncC.exe finished with error!

without chromaloc parameter, it is OK

**Comment by hyllm** [comment]
it is caused by chromaloc parameter... can you check please?

**Comment by rigaya** [comment]
Thank you for letting me know, shall be fixed in [QSVEnc 4.05](https://github.com/rigaya/QSVEnc/releases/tag/4.05).

**Comment by hyllm** [comment]
> Thank you for letting me know, shall be fixed in [QSVEnc 4.05](https://github.com/rigaya/QSVEnc/releases/tag/4.05).

thanks. will test later today. :-)

**Comment by rigaya** [comment]
I'll close this issue, as the problem should have been fixed.
