### ISSUE TITLE
using avsync bring up error message

### ISSUE THREAD

**Issue by bitcoin1192** [rigaya/QSVEnc#3]
I tried to encode a mkv file with avsync option enabled, but it always raised error on ivybridge cpu and up, 
while sandybridge cpu doing fine.
[log.txt](https://github.com/rigaya/QSVEnc/files/1076854/log.txt)

**Comment by rigaya** [comment]
I'll close this issue, as the problem should have been fixed in recent QSVEnc, which has changed handling of avsync.
