### ISSUE TITLE
Encoding in AAC HE-AACv2 creates unplayable Audio

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#32]
Encoding Audio to AAC HE-AACv2 creates unplayable Audio.

syntax:
`--audio-codec 1?aac  --audio-profile HE-AACv2
`
Checking with MEdia Info it shows the below:
```
Audio
ID                                       : 2
Format                                   : mp4a-40-29
Codec ID                                 : mp4a-40-29
```

Playing the Audio in any player does not work.

Encoding to AAC without any profiles and checking in Media Info 

using syntax:
`--audio-codec 1?aac
`
shows:

```
Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
```

**Comment by rigaya** [comment]
The default libavcodec aac encoder only supports AAC-LC.  --audio-profile is meant for other codecs or other aac encoders such as fdk-aac which supports HE-AAC. (fdk-aac cannot be redistributed, so it is not included in my build)

**Comment by quamt** [comment]
Oh I see, cause its Frauenhofer Codec 
How does it look with the implementation of this 
`https://www.openhub.net/p/fdk-aac` would that be possible?

**Comment by rigaya** [comment]
ffmpeg with fdk-aac requires --enable-nonfree flag anyway, so it can not be redistributed.

**Comment by quamt** [comment]
Oh I see.
But it's a bit confusing if it shows in the profiles, you might think it can be used for encoding.

**Comment by rigaya** [comment]
I'll close this issue as the topic has been answered.
