### ISSUE TITLE
How to build code on Debian/Ubuntu?

### ISSUE THREAD

**Issue by skysumbra** [rigaya/QSVEnc#34]
Hi
How to build code on Debian/Ubuntu ?
Could you provide step ?

**Comment by rigaya** [comment]
I've added docs showing how to build QSVEncC on linux.
https://github.com/rigaya/QSVEnc/blob/master/Build.en.md

CPUs starting from Broadwell and later will be supported for Linux build.

**Comment by skysumbra** [comment]
Very very  very  thanks! It's work.
i have question how to ./qsvencc with SO file merge ? 
li's quickly use vm 1 ,vm 2 (all same linux os)...

**Comment by rigaya** [comment]
> i have question how to ./qsvencc with SO file merge ?
> li's quickly use vm 1 ,vm 2 (all same linux os)...

I'm sorry but I could not get what you mean by "SO file merge".
If you are talking about static linking the libraries, it might be difficult as qsvencc depends on too many libraries from packages.

**Comment by skysumbra** [comment]
Yeap,so fiile mean libraries,
if i have embedded system or nas  for intel chilp, "qsvencc" maybe can convert video...
but  there systems not have general linux install command, ex:apt...
Could you know any  method?

**Comment by Saentist** [comment]
> Yeap,so fiile mean libraries,
> if i have embedded system or nas for intel chilp, "qsvencc" maybe can convert video...
> but there systems not have general linux install command, ex:apt...
> Could you know any method?

You mean "bundle" binary, with include all needed in one binary file?

**Comment by skysumbra** [comment]
Yeap ,yeap

**Comment by rigaya** [comment]
You need to build static link libraries for all the libraries such as libavformat, libavcodec, libmfx, libva and others required for qsvencc in order to include all needed in one binary file.

Also QSV feature might not actually run on VMs. (I've never tried.)

I'll close this issue as the normal way to build on Ubuntu is already shown.
