### ISSUE TITLE
Scaling happens before deinterlacing

### ISSUE THREAD

**Issue by pyahmed** [rigaya/QSVEnc#35]
First of all thanks for this wonderful tool, really helpful :-)

I've not found a way so set the order of deinterlacing and scaling. It seems that scaling is always applied first. Unfortunately this results in combing artefacts and no deinterlacing at all.

Use case: Deinterlace and scale 1920x1080i to 720p
Version used: 4.08
OS: Windows 10
GPU: Intel HD520
Input: 1920x1080i50 (MP4 and ProRes)

Command:
`QSVEncC64.exe -i prores_1080i50_sample.mov --vpp-deinterlace bob --output-res 1280x720 -o output.mp4`
or 
`QSVEncC64.exe -i prores_1080i50_sample.mov --output-res 1280x720 --vpp-deinterlace bob -o output.mp4`

Expected result:
Clean 1280x720p
Actual result:
Combing artefacts due to scaling before deinterlacing. Not really deinterlaced.

Is there a way to change the order of scaling/deinterlacing or is it just not possible at the moment to do these both steps in one run with qsvenc?

**Comment by rigaya** [comment]
I think the "--interlace" option missing is causing the issue.

It is required to set interlace flag for deinterlacing by "--interlace tff" or "--interlace bff" when using  --vpp-deinterlace.

**Comment by rigaya** [comment]
I'll close this issue, as methods of improvement are already shown.
