### ISSUE TITLE
422 conversion not working in 4.08

### ISSUE THREAD

**Issue by wwaag76** [rigaya/QSVEnc#36]
When trying to render a file which is 10bit 422 using the following command line:

 `qsvencc64 -i "H:\TestFootage\Panasonic S1-vlog\P1000045.MOV" --codec h264  --cqp 23 --quality fastest --colorrange tv  --fps 60000/1001 --avsync forcecfr  --audio-codec aac --audio-bitrate 128 --output-res 1920x1080 -o "C:\Temp\Test\Panny422.mp4" 2> “C:\Temp\422PannyError.txt”
`
I get the following error:
 
--------------------------------------------------------------------------------
C:\Temp\Test\Panny422.mp4
--------------------------------------------------------------------------------
Currently yuv422 surfaces are not supported by d3d9/d3d11 memory.
Switching to system memory.
Failed to initialize encode session. : undeveloped feature.

QSVEncC.exe finished with error!

Please advise.  Thanks.

**Comment by rigaya** [comment]
Would you share your system information?
YUV422 feature support is from Haswell Gen CPU/GPU or later.

**Comment by wwaag76** [comment]
It's an i8700K which I believe is CoffeeLake.  Here's info from a successful Nvenc render.

2020/11/10  08:31:50  --H:\TestFootage\Panasonic S1-vlog\P1000045_TMP.mp4
2020/11/10  08:31:50  ----------------------------------------------------------------------------------
2020/11/10  08:31:50  --NVEncC (x64) 5.19 (r1694) by rigaya, Nov  1 2020 05:46:38 (VC 1916/Win/avx2)
2020/11/10  08:31:50  --OS Version     Windows 10 x64 (19041)
2020/11/10  08:31:50  --CPU            Intel Core i7-8700K @ 3.70GHz [TB: 4.39GHz] (6C/12T)
2020/11/10  08:31:50  --GPU            #0: GeForce GTX 1050 Ti (768 cores, 1392 MHz)[PCIe3x16][456.38]
2020/11/10  08:31:50  --NVENC / CUDA   NVENC API 11.0, CUDA 11.1, schedule mode: auto
2020/11/10  08:31:50  --Input Buffers  CUDA, 20 frames
2020/11/10  08:31:50  --Input Info     avsw: h264(yuv422(10bit))->nv12 [-], 3840x2160, 24000/1001 fps
2020/11/10  08:31:50  --AVSync         forcecfr
2020/11/10  08:31:50  --Vpp Filters    copyHtoD
2020/11/10  08:31:50  --               cspconv(nv12 -> yv12)
2020/11/10  08:31:50  --               resize(spline36): 3840x2160 -> 1920x1080
2020/11/10  08:31:50  --               cspconv(yv12 -> nv12)
2020/11/10  08:31:50  --Output Info    H.264/AVC high @ Level auto
2020/11/10  08:31:50  --               1920x1080p 1:1 23.976fps (24000/1001fps)
2020/11/10  08:31:50  --               avwriter: h264 => mp4

**Comment by Saentist** [comment]
Is your Intel GPU enabled?

**Comment by wwaag76** [comment]
Yes.  Qsvenc works just fine with 420.

**Comment by rigaya** [comment]
As I were not able to reproduce the issue in my IceLake, KabyLake or Haswell environments (all without dGPU), I think it might be related to an environment with dGPU.

As there is no way to test this on my environments, I decided to avoid this issue by a workaround, switching the GPU based YUV422→YUV420 conversion which seems to be causing this issue to the CPU based one in [QSVEnc 4.09](https://github.com/rigaya/QSVEnc/releases/tag/4.09). Please have a try.

**Comment by wwaag76** [comment]
Works great.  Thanks a lot.

**Comment by rigaya** [comment]
Thanks for confirming, nice to hear it works!
