### ISSUE TITLE
V4.09 B_pyramid+PyramQPOffset gone

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#37]
In version 4.09 there is no B_pyramid and PyramQPOffset support anymore in HEVC, is this a bug? In version 4.06 it was supported. Tested on i7-7700K HD630 27.20.100.9021.

4.09:

![4_09](https://user-images.githubusercontent.com/18703109/99196697-6055b100-278e-11eb-810a-a9ff15e26745.jpg)

4.06:

![4_06](https://user-images.githubusercontent.com/18703109/99196698-6350a180-278e-11eb-8a18-92111c15ec78.jpg)

**Comment by rigaya** [comment]
Thank you for letting me know, shall be fixed in [QSVEnc 4.10](https://github.com/rigaya/QSVEnc/releases/tag/4.10).

![image](https://user-images.githubusercontent.com/815947/99663627-3b24b380-2aaa-11eb-83df-13ab7ef96362.png)
