### ISSUE TITLE
Driver bug 27.20.100.9025? 

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#40]
Intel recently released 27.20.100.9025 Beta, this one: https://downloadcenter.intel.com/download/30027

I have big issues using this driver with the h264 codec. Several bitrate modes (CQP, ICQ) doesn't work anymore and also extbrc and adapt-ltr. When I go back to 27.20.100.9021 all is working which could mean there is a driver bug but I'm not sure.

ExtBRC is not supported on current platform, disabled.
AdaptiveLTR is not supported on current platform, disabled.
Failed to initialize encoder. : invalid video parameters.
QSVEncC.exe finished with error!

ICQ without extbrc/adapt-ltr:

Failed to initialize encoder. : invalid video parameters.
QSVEncC.exe finished with error!

**Comment by mikk9** [comment]
I have tested with Handbrake and ICQ works there with this driver...

**Comment by rigaya** [comment]
[QSVEnc 4.11](https://github.com/rigaya/QSVEnc/releases/tag/4.11) adds workaround to avoid this issue, please have a try. I've checked that CQP, ICQ works with 9025 driver on Core i7 7700K.

**Comment by mikk9** [comment]
Yes this is fixed, thanks as usual. I found another issue. extbrc works with CBR but not with VBR. H265 VBR+extbrc works, H264 VBR+extbrc doesn't work.

**Comment by rigaya** [comment]
> H264 VBR+extbrc doesn't work.

Thanks for checking, [QSVEnc 4.12](https://github.com/rigaya/QSVEnc/releases/tag/4.12) shall avoid this error.
