### ISSUE TITLE
question about EnableMBQP

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#44]
In reference to this: https://community.intel.com/t5/Media-Intel-oneAPI-Video/HEVC-per-LCU-QP-Control-performance/td-p/1221825

H265 i9-9900K
without EnableMBQP= 180 fps
with EnableMBQP= 71 fps

Is it running with enabled or disabled "EnableMBQP" in QSVEnc?

**Comment by rigaya** [comment]
QSVEnc does not use "EnableMBQP", and it is always disabled.

EnableMBQP is a feature to specify QP per MB. However, I think it is not realistic to specify QP per MB from input file.

**Comment by mikk9** [comment]
Ok makes sense.
