### ISSUE TITLE
CQP wrong range HEVC 10 bit

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#45]
HEVC main 10 CQP:

qp-i value changed 52 -> 51, must be in range of 0-51
qp-p value changed 52 -> 51, must be in range of 0-51
qp-b value changed 55 -> 51, must be in range of 0-51

8 bit range max: 51
10 bit range max: 63
12 bit range max: 75

See here: https://github.com/Intel-Media-SDK/MediaSDK/issues/1980

This is signed value in [-51, 51] range if target encoding bit-depth for luma samples is 8 and this range is [-63, 63] for 10 bit-depth or [-75, 75] for 12 bit-depth respectively.
https://github.com/Intel-Media-SDK/MediaSDK/commit/3c8d8e299d0a4352b95a06c4e6ae0a3e0dd8ed6b#diff-223315361f714398d98dbd463b6f1872ccd45d4a192bc0da036fb2096c0ce868

**Comment by rigaya** [comment]
Thanks, shall be fixed in [QSVEnc 4.13](https://github.com/rigaya/QSVEnc/releases/tag/4.13).

**Comment by mikk9** [comment]
It works, thanks. I will close this thread.
