### ISSUE TITLE
how to pipe output immediately

### ISSUE THREAD

**Issue by zhuang0930** [rigaya/QSVEnc#49]
when i push yuv frames to QsvEncC via pipe("-") and encode it in h264,QsvEncC will output on pipe("-") for me.however,QsvEncC will always output on pipe more than 2 packets at the same time.As my question,what params i can set while i push yuv frames one by one and QsvEncC output packets one by one?

**Comment by rigaya** [comment]
There is no option to get packets one by one, as QSVEncC is simply writing the output bitstream to standard output (stdout) when using pipe. Generally, stdout is buffered, so packets are combined till the buffer gets full, and also the timing of the output will be delayed.

Therefore,  if you need to separate packets, you will need to parse the bitstream into each packets.

**Comment by zhuang0930** [comment]
Thank you！
