### ISSUE TITLE
Build on Ubuntu 20.10 fails with linker error.

### ISSUE THREAD

**Issue by leviculus** [rigaya/QSVEnc#50]
If Ubuntu 20.10 is known to fail builds, or is not intended to be supported in the future my apologies for opening the issue. 

When building QSVEnc I get the following error:

/usr/bin/ld: QSVPipeline/rgy_perf_monitor.o: relocation R_X86_64_PC32 against absolute symbol `_binary_PerfMonitor_perf_monitor_pyw_size' in section `.text' is disallowed
collect2: error: ld returned 1 exit status
make: *** [makefile:12: qsvencc] Error 1

Any idea why its failing?

Thank you!

**Comment by rigaya** [comment]
Thank you for letting me know the problem. Although I haven't checked Ubuntu 20.10 and were not able to reproduce the issue with Ubuntu 20.04, I've tried making a fix to avoid this problem in the latest revision.

Will you please update the code and have a try if it works?

**Comment by leviculus** [comment]
Thank you! 

The package compiled and ran successfully!

**Comment by leviculus** [comment]
Also thank you for such a quick response. These programs you've written are fantastic and a huge time saver thank you!
