### ISSUE TITLE
Encoding profile

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#51]
Is it possible to add more encoding profiles on Tigerlake (or Icelake) for HEVC? Tigerlake supports more than previous gens.

Hardware Accelerated Video Encode profile
Main
Main10
Main 4:2:2 10
Main 4:4:4
Main 4:4:4 10
https://cdrdv2.intel.com/v1/dl/getContent/631121

For decoding it can even support 12 bit.

**Comment by rigaya** [comment]
It's difficult right now as I haven't got a Tigerlake CPU, but I'll start implementing those features soon, as I'm planning to get a Rocketlake CPU which is also told to have12th Gen iGPU. (should come out soon)

**Comment by mikk9** [comment]
Yes it comes with Xe graphics. I found a Media Engine Programmer's Reference Manual for Iris Xe Max if it helps: https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-dg1-vol11-mediaengines.pdf
