### ISSUE TITLE
How do I copy a Closed Caption (CC) stream

### ISSUE THREAD

**Issue by rhscjohn-dev** [rigaya/QSVEnc#61]
I have a mepg-ts file that contains Closed Captions.  How do I copy the CC stream(s) when converting to type mp4?  Below is the JSON output from MediInfo.

{
"@type": "Text",
"@typeorder": "1",
"StreamOrder": "0-0",
"ID": "49-CC1",
"MenuID": "3",
"Format": "EIA-608",
"MuxingMode": "A/53 / DTVCC Transport",
"MuxingMode_MoreInfo": "Muxed in Video #1",
"Duration": "1628.460",
"BitRate_Mode": "CBR",
"Delay": "95293.118255556",
"Delay_Source": "Container",
"StreamSize": "0",
"Language": "en",
"extra": {
"CaptionServiceName": "CC1",
"CaptionServiceDescriptor_IsPresent": "Yes"
}
},
{
"@type": "Text",
"@typeorder": "2",
"StreamOrder": "0-0",
"ID": "49-CC3",
"MenuID": "3",
"Format": "EIA-608",
"MuxingMode": "A/53 / DTVCC Transport",
"MuxingMode_MoreInfo": "Muxed in Video #1",
"Duration": "1628.460",
"BitRate_Mode": "CBR",
"Delay": "95293.118255556",
"Delay_Source": "Container",
"StreamSize": "0",
"extra": {
"CaptionServiceName": "CC3",
"CaptionServiceDescriptor_IsPresent": "No"
}
}`
`

**Comment by rigaya** [comment]
Unfortunately, there is no support for Closed Caption (CC) stream.
