### ISSUE TITLE
Colorspace conversion not working (Linux)

### ISSUE THREAD

**Issue by bavdevc** [rigaya/QSVEnc#62]
Hello rigaya

current linux build (5.05) throws the following error when using --vpp-colorspace:

**colorspace: failed to load RGY_FILTER_COLORSPACE_CL(m_colorspace)**

I fixed that adding 3 lines to my local rgy_resource.cpp:

```
extern char _binary_QSVPipeline_rgy_filter_colorspace_func_h_start[];
extern char _binary_QSVPipeline_rgy_filter_colorspace_func_h_end[];
```
and
`    { _T("EXE_DATA"), _T("RGY_FILTER_COLORSPACE_CL"), _binary_QSVPipeline_rgy_filter_colorspace_func_h_start, _binary_QSVPipeline_rgy_filter_colorspace_func_h_end },
`
result: vpp-colorspace works (linux)

I don't know if that would also be your preferred solution.

kind regards

**Comment by rigaya** [comment]
Thank you for pointing out the issue and sharing the way to fix.

The 3 lines you have mentioned was missing, I've added this in 75a24af .

**Comment by bavdevc** [comment]
tested in 5.06 - working great
