### ISSUE TITLE
crash in AVIUtil if QSVEncC64.featureCache.txt exists

### ISSUE THREAD

**Issue by hide74** [rigaya/QSVEnc#66]
インストール後、AVIUtilのプラグインの設定画面で、QSVEncC.exeの場所を指定するとAVIUtilがクラッシュします。
confファイルを手動で設定した直後は、正しく設定画面が開き、閉じることができますが、再度、設定画面を開こうとすると同様にAVIUtilがクラッシュします。
色々試すと、QSVEncC64.exeと同じ場所にある、QSVEncC64.featureCache.txtを消すと、設定画面を開くことができますが、閉じて、そのファイルが生成されると、同様の症状になります。
QSVEncC 6.05及び6.04で確認しています。

**Comment by rigaya** [comment]
問題点をお知らせいただきありがとうございます。

一部環境で、ご指摘の問題が発生することを確認しました。QSVEncC64.featureCache.txtの有無がカギになっていることを教えていただいたおかげで、スムーズに調査でき、非常に助かりました。

次回リリース時には修正できるかと思います。

**Comment by hide74** [comment]
デバッグしてみました。
QSVEnc/frm/frmConfig_helper.hのSystem::Void getFeatures()で、CPUの周波数チェックのところで、周波数を返さない環境では、@が見つからず、compare_lenが-1となっているため、その後のString::Compareで落ちているようです。
環境を記載するのを忘れていましたが、GPUパススルーのqemu/kvm環境なのですが、その場合は周波数の情報が得られないようで、このような状態になっていました。
リリースで修正いただけるとのこと、ありがとうございます。

**Comment by rigaya** [comment]
原因はご指摘の通りで、おそらく昨日作成した e2f1fc0 で修正できると考えています。

別件の問題が残っていますので、そちらが解消できましたら更新させていただきます。

**Comment by rigaya** [comment]
お待たせいたしました。[QSVEnc 6.06](https://rigaya34589.blog.fc2.com/blog-entry-1401.html) にて修正できているかと思いますので、お試しいただけますでしょうか。

よろしくお願いいたします。

**Comment by hide74** [comment]
遅くなりました。
問題が解消されているのを確認しました。
ありがとうございました。
