### ISSUE TITLE
DX12 Video Encode

### ISSUE THREAD

**Issue by perrinpagess** [rigaya/QSVEnc#67]
Hello,

Intel added support for H264 and HEVC DX12 video encode on windows 11 with driver 9955, will you support this in future QSVEnc builds?

Thanks.

**Comment by rigaya** [comment]
By using DX12 Video Encode, an application will be able to pass DX12 video memory directly to hw encoder, which can increase performance which utilize DX12 API and use DX12 video memory. Games or graphic applications using DX12 API shall benefit from this feature.

In QSVEnc, we're not using DX12 API at all. Therefore, I'm not thinking to support this feature, as we won't have advantage from DX12 Video Encode feature.

**Comment by mikk9** [comment]
Agility SDK 1.700.10 is out with support for this, here is blog post from Microsoft:

https://devblogs.microsoft.com/directx/announcing-new-directx-12-feature-video-encoding/
