### ISSUE TITLE
--check-features decode support is incorrect

### ISSUE THREAD

**Issue by perrinpagess** [rigaya/QSVEnc#68]
Hello,

Running --check-features on an ice lake system (i5-1035G7) returns support for AV1 in the decode field, but ice lake does not support decode of AV1 as far as I'm aware?

Thanks.

**Comment by rigaya** [comment]
--check-features is showing the result of API function MFXVideoDECODE_Query, and it seems to return MFX_ERR_NONE when calling for AV1 on Icelake. However, I also think that Icelake does not support AV1 hw decode.

I'm not sure if I'm using MFXVideoDECODE_Query in a worng way or not, as it is working fine for other codes or other gen iGPUs.
