### ISSUE TITLE
Media SDK update to 2018 R1?

### ISSUE THREAD

**Issue by aluo-x** [rigaya/QSVEnc#7]
Seems like the Intel Media SDK got updated to 2018 R1 recently. Could we get something built against this?

Link here: https://software.intel.com/en-us/blogs/2018/03/07/whats-new-in-intel-media-sdk-2018-r1

**Comment by thx4ever** [comment]
Hey, can u add lookahead support to HEVC, cause Media SDK 2018R1 should support it, the implementation are like AVC described in release notes and documentation
