### ISSUE TITLE
Bug report and feedback QSVEnc 6.08

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#71]
I wanted to use this thread for some reports on version 6.08 because I think there are some issues. 

-B_Pyramid H264 is not supported in 6.08......supported in 5.06 (confirmed by feature check)
-d3d9 encoding Media SDK version misreport (1.255 on 6.08 and 1.35 on 5.06)

QSVEncC (x64) 5.06 (r2409) by rigaya, Jul 26 2021 10:32:10 (VC 1929/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1340)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v1.35
Async Depth    3 frames
Buffer Memory  d3d11, 122 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 24/1 fps
AVSync         cfr
Output         H.264/AVC(yuv420) High @ Level 4
               1920x1080p 1:1 24.000fps (24/1fps)
Target usage   1 - best
Encode Mode    Bitrate Mode - Lookahead
Bitrate        2500 kbps
Max Bitrate    15000 kbps
Lookahead      depth 100 frames, quality medium
Windowed RC    24 frames, Max 15000 kbps
QP Limit       min: none, max: none
Trellis        Auto
Ref frames     3 frames
Bframes        3 frames, B-pyramid: on
Max GOP Length 120 frames

B pyramid is not supported on current platform, disabled.
QSVEncC (x64) 6.08 (r2566) by rigaya, Feb  6 2022 02:00:21 (VC 1929/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz [TB: 3.14GHz] (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1340)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v2.06
Async Depth    3 frames
Buffer Memory  d3d11, 122 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 24/1 fps
AVSync         cfr
Output         H.264/AVC(yuv420) High @ Level 4
               1920x1080p 1:1 24.000fps (24/1fps)
Target usage   1 - best
Encode Mode    Bitrate Mode - Lookahead
Bitrate        2500 kbps
Max Bitrate    15000 kbps
Lookahead      depth 100 frames, quality medium
Windowed RC    off
QP Limit       min: none, max: none
Trellis        Auto
Ref frames     3 frames
Bframes        3 frames, B-pyramid: off
Max GOP Length 120 frames
Ext. Features  RepeatPPS 

B pyramid is not supported on current platform, disabled.
QSVEncC (x64) 6.08 (r2566) by rigaya, Feb  6 2022 02:00:21 (VC 1929/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1340)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v1.255
Async Depth    3 frames
Buffer Memory  d3d9, 122 work buffer
Input Info     avqsv: H.264/AVC, 1920x1080, 24/1 fps
AVSync         cfr
Output         H.264/AVC(yuv420) High @ Level 4
               1920x1080p 1:1 24.000fps (24/1fps)
Target usage   1 - best
Encode Mode    Bitrate Mode - Lookahead
Bitrate        2500 kbps
Max Bitrate    15000 kbps
Lookahead      depth 100 frames, quality medium
Windowed RC    off
QP Limit       min: none, max: none
Trellis        Auto
Ref frames     3 frames
Bframes        3 frames, B-pyramid: off
Max GOP Length 120 frames
Ext. Features  RepeatPPS

**Comment by mikk9** [comment]
d3d9 is crashing also in v6.08

MFXDEC: device kept on busy for 30s, unknown error occurred.
Break in task MFXDEC: gpu hang..
encoded 0 frames, 0.00 fps, 0.00 kbps, 0.00 MB
encode time 0:02:16, CPULoad: 12.5
QSVEncC.exe finished with error!

**Comment by mikk9** [comment]
RepeatPPS is new, isn't it? Is there a way to disable this?

**Comment by rigaya** [comment]
The issue --b-pyramid unavaliable was fixed in [QSVEnc 6.09](https://github.com/rigaya/QSVEnc/releases/tag/6.09).

It also adds option to disable RepeatPPS. Actually it's only new to the log, it was enabled by default but was not shown previously.
