### ISSUE TITLE
音视频 不同步

### ISSUE THREAD

**Issue by lxtx686** [rigaya/QSVEnc#74]
--avhw --audio-copy --codec h264 --la-icq 30 -u best --d3d11    用上面命令很多音视频不同步

-map 0 -c:v h264_qsv -preset veryslow -global_quality 23 -c:a copy  

同一个文件 用FFmpeg可以同步

**Comment by rigaya** [comment]
Please let me answer in English, as I cannot speak Chinese.

If your input file is VFR (variable frame rate), please have a try using ```--avsync vfr```, which might help improve your issue.

**Comment by lxtx686** [comment]
您好 ；视频文件没问题 ，编码出来音视频还是不同步 ，有时间的话您测试下。

Message ID: ***@***.***>

从网易163邮箱发来的超大附件
李荣浩-年少有为HD[瑞影].mpg (293.77M, 2022年5月24日 0:24 到期)
在线预览 | 下载

**Comment by rigaya** [comment]
Sorry, I cannot understand the Chinese meaning even with google translate.
