### ISSUE TITLE
failed to init opencl on Ivybridge CPU

### ISSUE THREAD

**Issue by klever1988** [rigaya/QSVEnc#75]
│libva info: VA-API version 1.14.0
                                                            │libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iH
                                                            │D_drv_video.so
                                                            │libva info: Found init function __vaDriverInit_1_14
                                                            │libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
                                                            │ init failed
                                                            │libva info: va_openDriver() returns 1
                                                            │libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i9
                                                            │65_drv_video.so
                                                            │libva info: Found init function __vaDriverInit_1_6
                                                            │libva info: va_openDriver() returns 0
                                                            │libva info: VA-API version 1.14.0
                                                            │libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iH                                                            │D_drv_video.so
                                                            │libva info: Found init function __vaDriverInit_1_14
                                                            │libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so                                                            │ init failed
                                                            │libva info: va_openDriver() returns 1
                                                            │libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i9                                                            │65_drv_video.so
                                                            │libva info: Found init function __vaDriverInit_1_6
                                                            │libva info: va_openDriver() returns 0
                                                            │**Error (clCreateContext): unknown error.**
                                                            │Failed to create OpenCL context.

**Comment by rigaya** [comment]
[Media SDK support](https://github.com/Intel-Media-SDK/MediaSDK) on Linux starts from Broadwell or later.

Unfortunately, IvyBridge is not supported on Linux systems.
