### ISSUE TITLE
AV1 encoding does not work

### ISSUE THREAD

**Issue by 0x22h** [rigaya/QSVEnc#77]
QSVEncC64 --check-environment
QSVEncC (x64) 7.04 (r2716) by rigaya, Jun 28 2022 12:42:35 (VC 1932/Win)
 Intel Media SDK API v2.07
 reader: raw, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, AV1]
Environment Info
OS : Windows 11 x64 (22621) [UTF-8]
CPU: 11th Gen Intel Core i7-11700K @ 3.60GHz [TB: 4.70GHz] (8C/16T)
RAM: Used 13875 MB, Total 32665 MB
GPU: Intel Arc A380  Graphics (128EU) 300-2450MHz (30.0.101.1736)

vspipe .\rawsource.vpy -a spath="./HEVC5.1_8bit_1080.mkv" -c y4m -   | QSVEncC64 --codec av1 --quality best --level high --profile 5.1 --colormatrix bt709 --colorprim bt709 --transfer bt709 --vbr 1000 -i - -o .\QSV_9\1000.av1

MFXENCODE:   Failed to get required buffer size for MFXENCODE: invalid video parameters.
allocD3D11: QSVAllocator: Failed CheckRequestType: undeveloped feature.
INPUT: allocWorkSurfaces:   Failed to allocate frames: undeveloped feature..
AllocFrames:   Failed to allocate frames for INPUT-MFXENCODE: undeveloped feature..RGYPoolAV: allocated 0, reused 0
RGYPoolAV: allocated 128, reused 0

QSVEncC.exe finished with error!
Error: fwrite() call failed when writing frame: 128, plane: 0, errno: 32
Output 145 frames in 1.12 seconds (130.04 fps)

**Comment by rigaya** [comment]
Unfortunately, AV1 hw encode should be supported from Intel Arc GPU or later, and not supported on 11700K (Rocketlake).

**Comment by 0x22h** [comment]
> Unfortunately, AV1 hw encode should be supported from Intel Arc GPU or later, and not supported on 11700K (Rocketlake).

Does this mean that it can only be support at 12xxx CPU + Arc Axxx GPU platform?

**Comment by rigaya** [comment]
> Does this mean that it can only be support at 12xxx CPU + Arc Axxx GPU platform?

I'm not sure, as Intel Arc GPU is still not available in Japan yet, and I haven't got chance to test.

It might be possible with Intel Arc GPU alone, but cannot say only from current Intel's publishments.

**Comment by 0x22h** [comment]
Thank you for your answer.
