### ISSUE TITLE
[REQ] Image sequence input

### ISSUE THREAD

**Issue by forart** [rigaya/QSVEnc#79]
Hi there and - as always - thanks for your cool work.

Since it doesn't support it yet - while FFMPEG does - it would be very useful to implement image sequence encoding.

This is especially useful for timelapses encoding, for example, but also for massive framesets (eg. [analog film scans](https://hackaday.io/list/175104-diy-film-scanners)).

Hope that inspires !

**Comment by rigaya** [comment]
Does this meaning encoding file like

input_0001.png
input_0002.png
input_0003.png
input_0004.png
...

This can be possible with commandline below.

```QSVEncC64.exe -i input_%04d.png -o output.mp4```

Current problem might be that the framerate is fixed to 25fps in this case.

**Comment by rigaya** [comment]
I'll have this issue closed as the topic has been answered.
