### ISSUE TITLE
Mistake in QSVEncC_Options.en.md ?

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#80]
In the QSVEncC_Options.en.md is written:

_Special encoding, such as encoding for Bluray, requires max bitrate to be set. In those cases VBR or AVBR must be used, as max bitrate can be set only with those modes._

However when I enable --avbr and --bluray for QSVEncC it results in the below error:

_Current encode mode (Bitrate Mode - AVBR) is not preferred for Bluray encoding,
since it cannot set Max Bitrate.
Please consider using Lookahead/VBR/CBR mode for Bluray encoding._

For the --quality setting it lists 
_best, higher, high, balanced(default), fast, faster, fastest_

Wasn't there settings _1, 2, 3, 4, 5, 6, 7_ too, that's equivalent to the above or did that change?

**Comment by rigaya** [comment]
I've fixed bluray documents in 00ffa24.

> Wasn't there settings 1, 2, 3, 4, 5, 6, 7 too, that's equivalent to the above or did that change?

It is **currently** equivalent to the above, but is will not be written in document, as it may change in the future.

**Comment by quamt** [comment]
Thank you.
