### ISSUE TITLE
Encoder crashes without error message

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#81]
When encoding a video with the below options in option file
```
--avhw
--codec hevc
--qvbr 3000
--qvbr-quality 19
--quality best
--output-depth 10
--max-bitrate 3000
--bframes 4
--ref  8
--b-pyramid
--i-adapt
--b-adapt
--weightb
--weightp
--mbbrc
--adapt-ltr
--sao all
--audio-copy
--output-res -2x1080
--vpp-resize auto
--vpp-resize-mode quality
--input-analyze 60
--vpp-edgelevel strength=10.0,threshold=16.0,black=0,white=0
--ssim
--psnr
```

The encoder ends at random points of the video.
When I remove 
```
--ssim
--psnr
```
It encodes normal.
Please let me know if you need a log file and which log level.

**Comment by quamt** [comment]
I did some more testing, strangely it seems to happen even with below option file

```
--avhw
--codec hevc
--qvbr 3000
--qvbr-quality 19
--quality best
--output-depth 10
--max-bitrate 3000
--bframes 4
--ref  8
--b-pyramid
--sao none
--audio-copy
--vpp-edgelevel strength=25,threshold=16.0,black=0,white=0
--ssim
--psnr
```

I tested _psnr_ and _ssim_ seperately and same crash.

**Comment by rigaya** [comment]
Although I was not able to reproduce the encoder crash, I think it's probably caused by ```--ssim``` and ```--psnr```, as the calcualted results were unstable.

I have made changes to improve stability of ```--ssim``` and ```--psnr``` in [QSVEnc 7.14](https://github.com/rigaya/QSVEnc/releases/tag/7.14), I hope this will fix.

**Comment by quamt** [comment]
Ok. I run a few tests with latest 7.14 and no more crashing.
Thank you.
