### ISSUE TITLE
tskip is always on in hevc 10bit

### ISSUE THREAD

**Issue by quamt** [rigaya/QSVEnc#82]
Using hevc 10 bit _tskip_ is always auto on.
The same goes for _WeightP WeightB_
Is tis supposed to be like this?

```
QSVEncC (x64) 7.13 (r2804) by rigaya, Aug 25 2022 13:12:55 (VC 1933/Win)
OS             Windows 11 x64 (22000) [UTF-8]
CPU Info       12th Gen Intel Core i9-12900K [4.92GHz] (8P+8E,16C/24T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [125W] (31.0.101.3222)
Media SDK      QuickSyncVideo (hardware encoder) PG, 3rd GPU, API v1.255
```

`Ext. Features  WeightP WeightB tskip ctu:64 sao:none`

**Comment by rigaya** [comment]
WeightP and WeightB is auto selected by ecoder by default, and it seems to be always enabled.

For tskip, it is possible to disable it by ```--no-tskip```.

**Comment by quamt** [comment]
OK. Thank you very much.
I couldn't find the` --no-tskip` in the `QSVEncC_Options.en.md` that's why I wondered if it can be disabled.
