### ISSUE TITLE
QSVEnc 7.14 no API 2.x support Iris Xe

### ISSUE THREAD

**Issue by mikk9** [rigaya/QSVEnc#84]
QSVEnc 7.14 doesn't use/detect API 2.x on Iris Xe. I tried the older 7.00 and this version detects API 2.x fine.

QSVEncC (x64) 7.14 (r2832) by rigaya, Sep  1 2022 12:45:15 (VC 1933/Win)
OS             Windows 10 x64 (19043) [UTF-8]
CPU Info       11th Gen Intel Core i7-1165G7 @ 2.80GHz (4C/8T) <Tigerlake>
GPU Info       Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1692)
Media SDK      QuickSyncVideo (hardware encoder) PG, 1st GPU, API v1.255
Async Depth    6 frames
Buffer Memory  d3d11, 27 work buffer
Input Info     AviSynth+ 3.7.0 r3382(yv12)->nv12 [AVX2], 1920x800, 24/1 fps
AVSync         cfr
Output         HEVC(yuv420) main @ Level 4 (high tier)
               1920x800p 249:250 24.000fps (24/1fps)
Target usage   1 - best
Encode Mode    Constant QP (CQP)
CQP Value      I:23  P:24  B:30
QP Limit       min: 1, max: 51
Trellis        Auto
Ref frames     5 frames
Bframes        14 frames, B-pyramid: on
Max GOP Length 120 frames
Ext. Features  WeightP WeightB QPOffset tskip ctu:64 sao:none 

QSVEncC (x64) 7.14 (r2832) by rigaya, Sep  1 2022 12:45:15 (VC 1933/Win)
 Intel Media SDK API v2.07
 reader: raw, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, AV1]
Environment Info
OS : Windows 10 x64 (19043) [UTF-8]
CPU: 11th Gen Intel Core i7-1165G7 @ 2.80GHz (4C/8T)
RAM: Used 6104 MB, Total 32494 MB
GPU: Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1692)

Media SDK Version: Hardware API v1.255

QSVEncC (x64) 7.00 (r2637) by rigaya, Apr  7 2022 13:18:13 (VC 1931/Win)
 Intel Media SDK API v2.06
 reader: raw, avi, avs, vpy, avsw, avhw [H.264/AVC, H.265/HEVC, MPEG2, VP8, VP9, AV1]
Environment Info
OS : Windows 10 x64 (19043) [UTF-8]
CPU: 11th Gen Intel Core i7-1165G7 @ 2.80GHz (4C/8T)
RAM: Used 6159 MB, Total 32494 MB
GPU: Intel Iris(R) Xe Graphics (96EU) 100-1300MHz [28W] (30.0.101.1692)

Media SDK Version: Hardware API v2.07

**Comment by rigaya** [comment]
The latest version is QSVEnc 7.16.

7.15 should has fix for this but has different problem, so please have a try with QSVEnc 7.16.

**Comment by mikk9** [comment]
It works, thanks. I thought 7.14 was the newest.
