### ISSUE TITLE
VP9 encoding in HDR

### ISSUE THREAD

**Issue by draco1544** [rigaya/QSVEnc#86]
Do you now how i can output a video in vp9 with the HDR (color space and meta data) from the source file ?

**Comment by rigaya** [comment]
Unfortunately not, as setting these metadata seems to be not supported in VP9 hw encoding, checked in both i5 1035G7 and i9 12900K.

**Comment by draco1544** [comment]
It's possible to transfer this HDR with an other software after encoding ?

**Comment by rigaya** [comment]
Sorry, I don't have any good idea about this.
