### ISSUE TITLE
The ARC a380 outputs av1 through the QSV plug-in in aviutl. Why is the speed slow?

### ISSUE THREAD

**Issue by henanzheng** [rigaya/QSVEnc#88]
The computer is AMD3700x+A380, and the video is 1920 * 1080. It was originally intended to speed up the output of av1 through the a380 hardware, but the speed is also very slow, only 27fps. The video card seems not to participate in the work, but the CPU takes up a lot. Is there any wrong setting? See the following figure:
![0001](https://user-images.githubusercontent.com/111262981/192004891-ff7c7b7b-d022-4b19-9458-66a0c2125e6b.png)
![0002](https://user-images.githubusercontent.com/111262981/192004900-cf315de3-43be-4ad7-afca-13fd48f42bc8.png)
![0003](https://user-images.githubusercontent.com/111262981/192004901-7b118949-bc9a-4cb7-b833-de848dae366c.png)

**Comment by rigaya** [comment]
Thank you for the details log and information.

Actually, output from Aviutl easily becomes CPU bound, as most of the steps are processed on CPU.

Overview of Aviutl process flow can be described as below.

![image](https://user-images.githubusercontent.com/815947/192073903-0c5e34ee-2d30-4b82-9928-ea9f472a7527.png)

It is likely that a process in before output plugin, which is somewhere surrounded by pink to become the major bottleneck.

The average processing time for the steps before output plugin is shown as "Average frame processing time" (or "平均帧获取时间" in Chinese), which you have 34.095ms. This means, even if the output(encode) step is fast enough, you cannot go beyond 1000/34.095=29.32fps, therefore 27.60fps is fair considering some encoding overhead.

Without any filters, it is possible to go up to 185fps as figures below, being GPU bound, in which a case "Average frame processing time" is tiny (3.428ms, but might not be realistic).

Unfortunately, it's difficult to tell from the output plugin that which step is slow, whether it is filters, exedit, or input.

![image](https://user-images.githubusercontent.com/815947/192074174-bb770cf1-8d71-4aa1-ae55-6101848b7f26.png)

![image](https://user-images.githubusercontent.com/815947/192074179-f982beb4-16a2-4d7d-9d7b-541ec9134ca9.png)

**Comment by henanzheng** [comment]
Thank you @ rigaya! I probably understand the meaning.
