### ISSUE TITLE
QSVEnc 3.06 option error for colorprim and transfer

### ISSUE THREAD

**Issue by proper88** [rigaya/QSVEnc#9]
I get these two errors

Error: Unknown value "bt2020" for "--colorprim"
Error: Unknown value "smpte2084" for "--transfer"

I take a look in qsv_prm.h, these values are missing

Version QSVEnc 3.03 is working, all versions after have these problems

**Comment by Revan654** [comment]
I'll add The Documentation states Colorspaces like Rec.2020 can be used, However the software does not support it (atlease not yet). Not sure if this is planned feature or if was just a mistype in the Docs.

Link: https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--colormatrix-string
Link: https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--colorprim-string
Link: https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--transfer-string

**Comment by rigaya** [comment]
Thanks for your report, QSVEnc 3.07 has added missing flags.
