### ISSUE TITLE
AV1 encoder and HDR

### ISSUE THREAD

**Issue by draco1544** [rigaya/QSVEnc#92]
The av1 encoder on arc gpu support av1 HDR 10bit hardware encoding ?

**Comment by henanzheng** [comment]
Yes, I seem to have completed the HDR to HDR conversion with the following command:
 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084

**Comment by henanzheng** [comment]
Add complete related instructions:
 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,500) --max-cll 1000,300

**Comment by rigaya** [comment]
[QSVEnc 7.21](https://github.com/rigaya/QSVEnc/releases/tag/7.21) adds support for HDR related options for AV1 encoding.
