### ISSUE TITLE
Bad vp9 quality

### ISSUE THREAD

**Issue by draco1544** [rigaya/QSVEnc#94]
I have a bad vp9 quality on every motion of the video. I suspect theses settings is responsible of my issue, how I can turn them back off ? 

`cop.AUDelimiter value changed off -> auto by driver

cop.PicTimingSEI value changed off -> auto by driver

cop.SingleSeiNalUnit value changed off -> auto by driver

cop2.BRefType value changed 1 -> 0 by driver

cop3.DirectBiasAdjustment value changed off -> auto by driver

cop3.GlobalMotionBiasAdjustment value changed off -> auto by driver`

**Comment by draco1544** [comment]
finally the issue is with icq, no matter which quality I choose the bitrate remains around 500 kb/s

**Comment by rigaya** [comment]
Yes, QSV VP9 hw encoding is known to be in poor quality. It is recommended to use other codecs for quality purpose.

>  I suspect theses settings is responsible of my issue, how I can turn them back off ?

These messages means that the driver has changed them, as they are not supported. Therefore, you cannot turn them on.
