### ISSUE TITLE
Error: Unknown param "swapuv" for option "--vpp-tweak"

### ISSUE THREAD

**Issue by Selur** [rigaya/QSVEnc#98]
When using 7.23 and `--vpp-tweak brightness=0,contrast=1,gamma=1,saturation=1,hue=0,swapuv=false`
I get  `Error: Unknown param "swapuv" for option "--vpp-tweak"`, which should work according to the [documentation](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-tweak-param1value1param2value2).
Without `,swapuv=false` everything works as it should.

**Comment by rigaya** [comment]
[QSVEnc 7.24](https://github.com/rigaya/QSVEnc/releases/tag/7.24) has added swapuv to [--vpp-tweak](https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--vpp-tweak-param1value1param2value2).

**Comment by Selur** [comment]
Thanks! :)
